using System.Text.Json;
using System.Diagnostics;
using DOCSeye.Core;
using DOCSeye.Storage.Sqlite;

public sealed partial class CHarness
{
    public void RunIdentityStorageCases()
    {
        Case01();Case02();Case03();Case04();Case05();Case06();Case07();Case08();Case09();Case10();Case11();
    }
    private void Case01()
    {
        var f=Fresh("c01-source");var old=Snap(f.Path);string runtimeDir=Path.Combine(Work,"c01-runtime");Directory.CreateDirectory(runtimeDir);using(var store=DndStore.Open(f.Path))using(var index=new RuntimeIndex(Path.Combine(runtimeDir,"index.db")))Expect(index.RebuildFrom(store)>0,"C-01 runtime index empty");
        string pipe="docseye-c01-"+Guid.NewGuid().ToString("N"),kernelDll=Path.Combine(Repo,"src","DOCSeye.Kernel","bin","Debug","net10.0","DOCSeye.Kernel.dll");var psi=new ProcessStartInfo("dotnet"){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true};psi.ArgumentList.Add(kernelDll);psi.Environment["DOCSEYE_PIPE"]=pipe;psi.Environment["PATH"]=SqliteNative+Path.PathSeparator+Environment.GetEnvironmentVariable("PATH");using(var kernel=Process.Start(psi)??throw new InvalidOperationException("C-01 kernel start failed")){var opened=Rpc(pipe,"document.open",new{path=f.Path});Expect(opened.GetProperty("writeAuthority").GetBoolean(),"C-01 kernel open nonwritable");kernel.Kill(true);kernel.WaitForExit();Expect(kernel.HasExited,"C-01 kernel did not die");}
        Directory.Delete(runtimeDir,true);string moved=Path.Combine(Work,"c01-moved.dnd");string shell=Run(Node,ShellMove,f.Path,moved);Expect(File.Exists(moved)&&!File.Exists(f.Path),"C-01 carrier move failed");int recovered;using(var s=NativeDocumentSession.Open(moved,true)){Expect(s.WriteAuthority,"C-01 artifact-only reopen nonwritable");recovered=RecoverSentinels(s.LoadState(),f.Manifest);Expect(recovered==32,"C-01 sentinel recovery !=32");}ScorePositive("P-01","C-01",recovered,32,"32 frozen sentinel identities recovered from artifact only after kernel/runtime loss and carrier move");
        var now=Snap(moved);Expect(old.FamilyId==now.FamilyId&&old.BranchId==now.BranchId&&old.RevisionId==now.RevisionId&&old.SemanticRoot==now.SemanticRoot,"C-01 identity/root changed");Pass("C-01","committed N-001 and 32 sentinels","kill kernel; delete runtime; move carrier; reopen","exact artifact-only recovery","exact artifact-only recovery",old,now,SentinelIds(f.Manifest),"native","kernel_kill/runtime_delete/carrier_move",new{sentinels="32/32",runtime_deleted=true,shelleye=JsonDocument.Parse(shell).RootElement.Clone(),identity_remints=0});
    }
    private void Case02()
    {
        var f=Fresh("c02");var old=Snap(f.Path);string rootBefore;int objectsBefore;using(var s=DndStore.Open(f.Path)){rootBefore=Convert.ToHexString(s.LoadState().ComputeRoot()).ToLowerInvariant();objectsBefore=s.LoadState().Objects.Count;s.VacuumAndRebuildIndexes();s.RebuildMerkleCache();}using(var s=DndStore.Open(f.Path)){Expect(s.Validate(true).Writable,"C-02 maintenance invalidated artifact");Expect(Convert.ToHexString(s.LoadState().ComputeRoot()).ToLowerInvariant()==rootBefore&&s.LoadState().Objects.Count==objectsBefore,"C-02 semantic change after maintenance");}var now=Snap(f.Path);Expect(old.RevisionId==now.RevisionId&&old.SemanticRoot==now.SemanticRoot,"C-02 head/root changed");Pass("C-02","valid head/root","VACUUM; REINDEX; Merkle cache rebuild","same revision/root and semantics","same revision/root and semantics",old,now,[],"native","sqlite_vacuum_reindex_merkle_rebuild",new{semantic_root_before=rootBefore,objects_before=objectsBefore,artifact_bytes_rewritten=old.Sha256!=now.Sha256});
    }
    private void Case03()
    {
        var f=Fresh("c03");var old=Snap(f.Path);using var s=NativeDocumentSession.Open(f.Path,true);var before=s.LoadState();var duplicates=before.Objects.Values.Where(o=>!o.Retired&&o.Type=="text_block"&&o.Data.TryGetValue("text",out var t)&&Equals(t,"Identity must never follow duplicate text.")).ToArray();Expect(duplicates.Length>=2&&duplicates[0].ParentId!=duplicates[1].ParentId,"C-03 duplicate text fixture missing");var rows=before.Objects.Values.Where(o=>!o.Retired&&o.Type=="table_row"&&o.ParentId is not null).GroupBy(o=>o.ParentId).First(g=>g.Count()>=2).OrderBy(o=>o.Order).ToArray();Guid moved=duplicates[0].Id,row=rows[0].Id;var b=s.BeginTransaction();b.MoveObject(moved,duplicates[1].ParentId!.Value,0);b.ReorderObject(row,rows.Length-1);var r=s.CommitTransaction(b,s.ReadHead().RevisionId,"C-03");Expect(r.Success,"C-03 commit failed: "+r.Classification);var after=s.LoadState();Expect(after.Objects[moved].Id==moved&&after.Objects[moved].ParentId==duplicates[1].ParentId,"C-03 paragraph ID/location wrong");var rowOrderAfter=after.Objects.Values.Where(o=>!o.Retired&&o.Type=="table_row"&&o.ParentId==rows[0].ParentId).OrderBy(o=>o.Order).ThenBy(o=>Ids.Lower(o.Id),StringComparer.Ordinal).Select(o=>o.Id).ToArray();Expect(after.Objects[row].Id==row&&rowOrderAfter[^1]==row,"C-03 row ID/sibling location wrong");var now=Snap(f.Path);Pass("C-03","duplicate paragraphs and rows","move paragraph and reorder duplicate row","same moved IDs at new locations","same moved IDs at new locations",old,now,[moved,row],"native","semantic_move_and_reorder",new{paragraph_id_preserved=true,row_id_preserved=true,coordinate_match_rebinds=0});
    }
    private void Case04()
    {
        var f=Fresh("c04");var old=Snap(f.Path);Guid victim,replacement;RevisionHead retiredHead;using(var s=NativeDocumentSession.Open(f.Path,true)){var st=s.LoadState();var o=st.Objects.Values.First(x=>!x.Retired&&x.Type=="text_block"&&!st.Objects.Values.Any(c=>!c.Retired&&c.ParentId==x.Id)&&!st.Boundaries.Values.Any(q=>q.OwnerId==x.Id));victim=o.Id;var stale=new PortableWriteHandle(st.FamilyId,st.BranchId,victim,s.ReadHead().RevisionId);var b=s.BeginTransaction();b.RetireObject(victim,RetiredResolution.Destroyed);replacement=b.CreateObject(o.Type,o.ParentId,o.Role,new Dictionary<string,object?>(o.Data,StringComparer.Ordinal));var rr=s.CommitTransaction(b,s.ReadHead().RevisionId,"C-04-retire");Expect(rr.Success,"C-04 retire failed");retiredHead=rr.Head!;var staleResult=s.CommitObjectData(stale,new(StringComparer.Ordinal){{"text","must-not-hit-replacement"}},"C-04-stale");Expect(!staleResult.Success&&staleResult.Classification=="stale_revision","C-04 stale old handle not refused");var currentOld=new PortableWriteHandle(st.FamilyId,st.BranchId,victim,retiredHead.RevisionId);var retired=s.CommitObjectData(currentOld,new(StringComparer.Ordinal){{"text","must-not-hit-replacement"}},"C-04-retired");Expect(!retired.Success&&retired.Classification=="retired_object","C-04 retired object not refused");var mid=s.LoadState();Expect(mid.Objects[victim].Retired&&mid.Retired[victim].Resolution==RetiredResolution.Destroyed&&mid.Objects.ContainsKey(replacement)&&!mid.Objects[replacement].Retired,"C-04 retirement/replacement wrong");var gc=s.BeginTransaction();Expect(gc.GarbageCollectRetiredWitnesses(1000)==1,"C-04 lineage GC did not collect witness");var gr=s.CommitTransaction(gc,retiredHead.RevisionId,"C-04-gc");Expect(gr.Success,"C-04 GC commit failed");Expect(s.LoadState().Retired[victim].Resolution==RetiredResolution.UnknownRetired,"C-04 witness not unknown_retired");}
        var now=Snap(f.Path);Pass("C-04","retained handle to paragraph","delete object; create byte-identical replacement; lineage GC","old destroyed/later unknown_retired; replacement new ID live","destroyed -> unknown_retired; replacement live",old,now,[victim,replacement],"native","retire_replace_stale_handle_gc",new{old_id=Ids.Lower(victim),replacement_id=Ids.Lower(replacement),same_id=false,stale_handle="stale_revision",current_old_handle="retired_object",final_retirement="unknown_retired"});
    }
    private void Case05()
    {
        var f=Fresh("c05");var old=Snap(f.Path);SemanticState source;using(var s=NativeDocumentSession.Open(f.Path,true))source=s.LoadState();Guid annotated=source.Boundaries.Values.First().OwnerId;var target=Branching.Clone(source);var originalPublic=Branching.PublicIds(target);var originalBoundaries=target.Boundaries.Keys.ToHashSet();var map1=Branching.PasteObjectSubgraph(target,source,annotated,null,true);var boundaries1=target.Boundaries.Keys.Where(x=>!originalBoundaries.Contains(x)).ToHashSet();var before2Public=Branching.PublicIds(target);var before2Boundaries=target.Boundaries.Keys.ToHashSet();var map2=Branching.PasteObjectSubgraph(target,source,annotated,null,true);var boundaries2=target.Boundaries.Keys.Where(x=>!before2Boundaries.Contains(x)).ToHashSet();Expect(map1.Values.All(x=>!originalPublic.Contains(x))&&map2.Values.All(x=>!before2Public.Contains(x))&&boundaries1.Count>0&&boundaries2.Count>0&&!boundaries1.Overlaps(boundaries2),"C-05 copy reused public IDs/boundaries");Guid parentRev=target.RevisionId;target.RevisionId=Ids.NewV4();target.Sequence++;string outp=Persist(Path.Combine(Work,"c05-result.dnd"),target,[parentRev]);var now=Snap(outp);Pass("C-05","block and duplicate-row source","within-branch deep copy twice with retained annotations","every copied occurrence/boundary ID reminted; asset digest may share","all copied object and boundary IDs reminted",old,now,map1.Values.Concat(map2.Values),"native","two_annotated_subgraph_pastes",new{copy1_objects=map1.Count,copy2_objects=map2.Count,copy1_boundaries=boundaries1.Count,copy2_boundaries=boundaries2.Count,shared_semantic_ids=0,asset_digest_set_equal=target.Assets.Keys.ToHashSet().SetEquals(source.Assets.Keys)});
    }
    private void Case06()
    {
        var f=Fresh("c06");var old=Snap(f.Path);SemanticState source;RevisionHead sourceHead;using(var s=NativeDocumentSession.Open(f.Path,true)){source=s.LoadState();sourceHead=s.ReadHead();}var fork=Branching.Fork(source);Expect(fork.State.FamilyId==source.FamilyId&&fork.State.BranchId!=source.BranchId,"C-06 family/branch wrong");Expect(!Branching.PublicIds(source).Overlaps(Branching.PublicIds(fork.State)),"C-06 public ID reuse");Expect(fork.SourceToCurrent.All(k=>fork.State.OriginRefs.TryGetValue(k.Value,out var o)&&o.SourceId==k.Key&&o.SourceBranchId==source.BranchId),"C-06 origin map incomplete");string outp=Persist(Path.Combine(Work,"c06-fork.dnd"),fork.State,[sourceHead.RevisionId]);Guid sourceObj=source.Objects.Values.First(o=>!o.Retired&&o.Type=="text_block").Id;using(var s=NativeDocumentSession.Open(outp,true)){string beforeSha=Sha(outp);var denied=s.CommitObjectData(new(source.FamilyId,source.BranchId,sourceObj,source.RevisionId),new(StringComparer.Ordinal){{"text","wrong branch"}},"C-06-stale");Expect(!denied.Success&&denied.Classification=="cross_branch_handle"&&Sha(outp)==beforeSha,"C-06 source handle actuated fork");}var now=Snap(outp);Pass("C-06","one live branch with retained ranges","Save As / explicit fork","same family, new branch, 100% public ID/boundary remint, exact origin map","same family; new branch; 100% remint; source handle refused",old,now,fork.SourceToCurrent.Values,"native","explicit_branch_fork",new{same_family=true,new_branch=true,public_remint_percent=100,boundary_remint_percent=100,origin_map_count=fork.State.OriginRefs.Count,source_handle="cross_branch_handle"});
    }
    private void Case07()
    {
        var f=Fresh("c07");var old=Snap(f.Path);SemanticState source;using(var s=NativeDocumentSession.Open(f.Path,true))source=s.LoadState();var dup=Branching.IndependentDuplicate(source);var templ=Branching.InstantiateTemplate(source);Expect(dup.State.FamilyId!=source.FamilyId&&dup.State.BranchId!=source.BranchId&&templ.State.FamilyId!=source.FamilyId&&templ.State.BranchId!=source.BranchId&&dup.State.FamilyId!=templ.State.FamilyId,"C-07 new family/branch contract failed");Expect(!Branching.PublicIds(source).Overlaps(Branching.PublicIds(dup.State))&&!Branching.PublicIds(source).Overlaps(Branching.PublicIds(templ.State))&&!Branching.PublicIds(dup.State).Overlaps(Branching.PublicIds(templ.State)),"C-07 public ID collision");string dp=Persist(Path.Combine(Work,"c07-duplicate.dnd"),dup.State),tp=Persist(Path.Combine(Work,"c07-template.dnd"),templ.State);var now=Snap(dp);var ts=Snap(tp);Pass("C-07","native fixture and template source","independent duplicate and template instantiation","new family/branch/all public IDs; bounded provenance only","two distinct new families/branches and disjoint public IDs",old,now,Branching.PublicIds(dup.State),"native","independent_duplicate_and_template_instance",new{duplicate=now,template=ts,duplicate_public_ids=Branching.PublicIds(dup.State).Count,template_public_ids=Branching.PublicIds(templ.State).Count,public_id_collisions=0});
    }
    private void Case08()
    {
        var f=Fresh("c08-base");var old=Snap(f.Path);string a=Path.Combine(Work,"c08-a.dnd"),b=Path.Combine(Work,"c08-b.dnd");CopyArtifact(f.Path,a);CopyArtifact(f.Path,b);RevisionHead baseHead,ha,hb;SemanticState baseState;using(var s=NativeDocumentSession.Open(f.Path,true)){baseHead=s.ReadHead();baseState=s.LoadState();}var targets=baseState.Objects.Values.Where(o=>!o.Retired&&o.Type=="text_block").Take(2).ToArray();using(var s=NativeDocumentSession.Open(a,true)){var r=s.CommitObjectData(new(baseHead.FamilyId,baseHead.BranchId,targets[0].Id,baseHead.RevisionId),Change(targets[0],"c08","left"),"C-08-left");Expect(r.Success,"C-08 left failed");ha=r.Head!;}using(var s=NativeDocumentSession.Open(b,true)){var r=s.CommitObjectData(new(baseHead.FamilyId,baseHead.BranchId,targets[1].Id,baseHead.RevisionId),Change(targets[1],"c08","right"),"C-08-right");Expect(r.Success,"C-08 right failed");hb=r.Head!;}using(var sa=DndStore.Open(a))using(var sb=DndStore.Open(b)){var presentation=sa.PresentWith(sb);Expect(presentation.Classification=="divergent_heads"&&!presentation.CanWrite&&presentation.CommonRevisionId==baseHead.RevisionId,"C-08 divergence not detected");}
        SemanticState left,right;using(var sa=NativeDocumentSession.Open(a,true))left=sa.LoadState();using(var sb=NativeDocumentSession.Open(b,true))right=sb.LoadState();var explicitFork=Branching.Fork(left);Persist(Path.Combine(Work,"c08-explicit-fork.dnd"),explicitFork.State,[ha.RevisionId]);var merged=Branching.MergeDisjoint(baseState,left,right,Ids.NewV4());string mp=Persist(Path.Combine(Work,"c08-explicit-merge.dnd"),merged,[ha.RevisionId,hb.RevisionId]);var now=Snap(mp);Pass("C-08","byte-identical A/B replicas","different commits from same base; coexist; explicit fork/merge","divergent_heads; writes stopped; explicit resolution only","divergent_heads then explicit fork and two-parent merge",old,now,[targets[0].Id,targets[1].Id],"native","replica_divergence_then_explicit_resolution",new{base_revision=Ids.Lower(baseHead.RevisionId),head_a=Ids.Lower(ha.RevisionId),head_b=Ids.Lower(hb.RevisionId),classification="divergent_heads",implicit_linearizations=0,explicit_fork_branch=Ids.Lower(explicitFork.State.BranchId),merge_parent_count=2});
    }
    private void Case09()
    {
        var f=Fresh("c09");var old=Snap(f.Path);SemanticState source;using(var s=NativeDocumentSession.Open(f.Path,true))source=s.LoadState();var fork=Branching.Fork(source);Guid sourceObj=source.Objects.Values.First(o=>!o.Retired&&o.Type=="text_block").Id;var target=Branching.Clone(fork.State);var map=Branching.PasteObjectSubgraph(target,source,sourceObj,null,true);Guid pasted=map[sourceObj],parentRev=target.RevisionId;target.RevisionId=Ids.NewV4();target.Sequence++;string outp=Persist(Path.Combine(Work,"c09-paste.dnd"),target,[parentRev]);using(var s=NativeDocumentSession.Open(outp,true)){string before=Sha(outp);var denied=s.CommitObjectData(new(source.FamilyId,source.BranchId,sourceObj,source.RevisionId),new(StringComparer.Ordinal){{"text","must not actuate paste"}},"C-09-source-handle");Expect(!denied.Success&&denied.Classification=="cross_branch_handle"&&Sha(outp)==before,"C-09 stale source handle wrote target");Expect(s.LoadState().Objects.ContainsKey(pasted),"C-09 pasted object absent");}Expect(pasted!=sourceObj&&!source.Objects.ContainsKey(pasted),"C-09 paste reused source ID");var now=Snap(outp);Pass("C-09","source and forked branch","cross-branch paste plus stale source-branch handle","paste subgraph reminted; stale handle refused","paste reminted; source handle cross_branch_handle",old,now,map.Values,"native","cross_branch_paste_and_source_handle",new{source_id=Ids.Lower(sourceObj),pasted_id=Ids.Lower(pasted),source_handle="cross_branch_handle",cross_branch_writes=0});
    }
    private void Case10()
    {
        var f=Fresh("c10");var old=Snap(f.Path);Guid target=Guid.Parse(f.Manifest.Sentinels["text_blocks"][0]);string dup=Path.Combine(Work,"c10-duplicate.dnd"),broken=Path.Combine(Work,"c10-broken-ref.dnd");CopyArtifact(f.Path,dup);CopyArtifact(f.Path,broken);string hex=Convert.ToHexString(Ids.RfcBytes(target));Sql(dup,$"INSERT INTO objects(id,type,parent_id,order_key,role,cbor,retired) SELECT id,type,parent_id,order_key,role,cbor,retired FROM objects WHERE id=X'{hex}' LIMIT 1;");Sql(broken,$"UPDATE objects SET parent_id=randomblob(16) WHERE id=X'{hex}';");AssertInvalidNoWrite(dup,"duplicate_id",target);AssertInvalidNoWrite(broken,"broken_reference",target);var now=Snap(dup);Pass("C-10","independently rewritten DND","duplicate one public object ID and break one typed reference","validation failure; artifact non-writable","duplicate_id and broken_reference vectors both non-writable",old,now,[target],"native","raw_sql_duplicate_id_and_broken_reference",new{duplicate_vector="duplicate_id/non_writable",broken_reference_vector="broken_reference/non_writable",auto_repairs=0,identity_steals=0});
    }
    private void Case11()
    {
        var f=Fresh("c11");var old=Snap(f.Path);Guid boundary=Guid.Parse(f.Manifest.Sentinels["retained_boundaries"][0]),target=Guid.Parse(f.Manifest.Sentinels["text_blocks"][0]);string dup=Path.Combine(Work,"c11-duplicate-boundary.dnd"),bad=Path.Combine(Work,"c11-bad-root.dnd");CopyArtifact(f.Path,dup);CopyArtifact(f.Path,bad);string bh=Convert.ToHexString(Ids.RfcBytes(boundary));Sql(dup,$"INSERT INTO boundaries(id,owner_id,scalar_offset,affinity,state,cbor) SELECT id,owner_id,scalar_offset,affinity,state,cbor FROM boundaries WHERE id=X'{bh}' LIMIT 1;");Sql(bad,"UPDATE head SET semantic_root=zeroblob(32) WHERE id=1;");AssertInvalidNoWrite(dup,"duplicate_id",target);AssertInvalidNoWrite(bad,"invalid_root",target);var now=Snap(dup);Pass("C-11","valid retained anchors/root","duplicate boundary ID and mismatched semantic root","validation failure; artifact non-writable","duplicate boundary and invalid root vectors non-writable",old,now,[boundary,target],"native","raw_sql_duplicate_boundary_and_root_tamper",new{duplicate_boundary="duplicate_id/non_writable",root_mismatch="invalid_root/non_writable",boundary_alias_accepted=false,root_regenerated=false});
    }
}
