using System.Security.Cryptography;
using System.Text;
using DOCSeye.Core;
using DOCSeye.Fixtures;
using DOCSeye.Providers;
using DOCSeye.Storage.Sqlite;

public sealed partial class CHarness
{
    public void RunConcurrencyRenderCases()
    {
        Case24();Case25();Case26();Case27();Case28();Case29();Case30();Case31();Case32();
    }

    private void Case24()
    {
        var f=Fresh("c24");var old=Snap(f.Path);using var s=NativeDocumentSession.Open(f.Path,true);var h=s.ReadHead();var st=s.LoadState();var o=Obj(st,x=>x.Type=="text_block"&&x.Role=="body");var good=s.CommitObjectData(new(h.FamilyId,h.BranchId,o.Id,h.RevisionId),Change(o,"c24",1),"C-24-good");Expect(good.Success,"C-24 R+1 commit failed");string sha=Sha(f.Path);var stale=s.CommitObjectData(new(h.FamilyId,h.BranchId,o.Id,h.RevisionId),Change(o,"c24",2),"C-24-stale");Expect(!stale.Success&&stale.Classification=="stale_revision"&&Sha(f.Path)==sha,"C-24 stale R write occurred");var now=Snap(f.Path);Pass("C-24","valid handle at revision R","commit R+1 then attempt R-conditioned mutation","stale_revision and zero write","stale_revision",old,now,[o.Id],"native","revision_guard_after_new_commit",new{classification=stale.Classification,stale_write_bytes=0});
    }

    private void Case25()
    {
        var f=Fresh("c25-base");var old=Snap(f.Path);string a=Path.Combine(Work,"c25-a.dnd"),b=Path.Combine(Work,"c25-b.dnd");CopyArtifact(f.Path,a);CopyArtifact(f.Path,b);SemanticState st;RevisionHead h;using(var s=DndStore.Open(f.Path)){st=s.LoadState();h=s.ReadHead();}var os=st.Objects.Values.Where(o=>!o.Retired&&o.Type=="text_block"&&o.Role=="body").Take(2).ToArray();using(var sa=NativeDocumentSession.Open(a,true))Expect(sa.CommitObjectData(new(h.FamilyId,h.BranchId,os[0].Id,h.RevisionId),Change(os[0],"writer","A"),"C-25-a").Success,"C-25 A failed");using(var sb=NativeDocumentSession.Open(b,true))Expect(sb.CommitObjectData(new(h.FamilyId,h.BranchId,os[1].Id,h.RevisionId),Change(os[1],"writer","B"),"C-25-b").Success,"C-25 B failed");using(var sa=DndStore.Open(a))using(var sb=DndStore.Open(b)){var pres=sa.PresentWith(sb);Expect(pres.Classification=="divergent_heads"&&!pres.CanWrite,"C-25 unresolved heads writable");}var now=Snap(a);Pass("C-25","two writers from same base revision","observe both unresolved heads","divergent_heads; writes refused pending explicit resolution","divergent_heads",old,now,os.Select(x=>x.Id),"native","two_writer_same_base_presentation",new{classification="divergent_heads",writes_pending_resolution=0});
    }

    private void Case26()
    {
        byte[] asset=new byte[2*1024*1024+17];for(int i=0;i<asset.Length;i++)asset[i]=(byte)(i*31+7);var outcomes=new List<object>();string final="";ArtifactSnapshot finalOld=default!;Guid finalTarget=Guid.Empty,finalFigure=Guid.Empty;int successDeltaCoverage=0;
        foreach(var fault in new[]{TransactionFaultPoint.BeforeSemanticWrite,TransactionFaultPoint.AfterSemanticRecords,TransactionFaultPoint.DuringAssetWrite,TransactionFaultPoint.AfterRoot,TransactionFaultPoint.AfterHeadWrite,TransactionFaultPoint.DiskFull,TransactionFaultPoint.None})
        {
            var f=Fresh("c26-"+fault);var pre=Snap(f.Path);string key="C-26-"+fault;using(var s=NativeDocumentSession.Open(f.Path,true))
            {
                var st=s.LoadState();Guid target=Obj(st,o=>o.Type=="text_block"&&o.Role=="body").Id,fig=st.Objects.Values.First(o=>!o.Retired&&o.Type=="figure").Id;var tx=s.BeginTransaction();tx.SetObjectProperty(target,"c26_marker",fault.ToString());using var ms=new MemoryStream(asset,false);var r=s.CommitTransactionWithAsset(tx,ms,s.ReadHead().RevisionId,key,fig,256*1024,fault);Expect(fault==TransactionFaultPoint.None?r.Success:!r.Success,"C-26 fault outcome wrong: "+fault);finalTarget=target;finalFigure=fig;
                if(fault==TransactionFaultPoint.None)
                {
                    Expect(r.Delta is not null,"C-26 committed delta missing");var d=r.Delta!;successDeltaCoverage=(d.ChangedObjects.Contains(target)?1:0)+(d.ChangedObjects.Contains(fig)?1:0)+(d.ChangedAssets.Count==1?1:0);Expect(successDeltaCoverage==3,"C-26 committed delta omitted semantic/asset change");
                }
                else Expect(s.QueryIdempotency(key) is null,"C-26 failed transaction left acknowledged/idempotent outcome: "+fault);
            }
            using(var s=NativeDocumentSession.Open(f.Path,true))
            {
                Expect(s.WriteAuthority,"C-26 post-fault artifact non-writable");var post=Snap(f.Path);if(fault==TransactionFaultPoint.None)Expect(post.RevisionId!=pre.RevisionId,"C-26 success did not publish new");else Expect(post.RevisionId==pre.RevisionId&&post.SemanticRoot==pre.SemanticRoot,"C-26 fault exposed partial state: "+fault);outcomes.Add(new{fault=fault.ToString(),outcome=fault==TransactionFaultPoint.None?"new":"old"});
            }
            if(fault==TransactionFaultPoint.None){final=f.Path;finalOld=pre;}
        }
        Expect(final.Length>0,"C-26 success vector absent");ScorePositive("P-04","C-26",7,7,"six injected failures recovered old and no-fault recovered new");ScorePositive("P-06","C-26",successDeltaCoverage,3,"streamed commit delta covered changed semantic target, figure, and asset commitment");var now=Snap(final);Pass("C-26","multi-object transaction plus 2 MiB streamed asset","fault before/during semantic/blob/root/head publication plus disk full","every recovery exactly old or new","old_or_new_only",finalOld,now,[finalTarget,finalFigure],"native/sqlite","streamed_transaction_fault_matrix",new{faults=outcomes,old_or_new_numerator=7,old_or_new_denominator=7,delta_coverage_numerator=successDeltaCoverage,delta_coverage_denominator=3,partial_acknowledgements=0});
    }

    private void Case27()
    {
        var f=Fresh("c27");var old=Snap(f.Path);using var s=NativeDocumentSession.Open(f.Path,true);var h=s.ReadHead();Guid target=s.QueryObjects("text_block","body").First().Id;var tx=s.BeginTransaction();tx.SetObjectProperty(target,"c27",1);var committed=s.CommitTransaction(tx,h.RevisionId,"c27-key");Expect(committed.Success&&committed.Head is not null,"C-27 initial commit failed");var committedHead=committed.Head!;var retryTx=new SemanticTransactionBuilder(tx.BaseState);retryTx.SetObjectProperty(target,"c27",1);var retry=s.CommitTransaction(retryTx,h.RevisionId,"c27-key");Expect(retry.Success&&retry.Classification=="committed_known"&&retry.Head!.RevisionId==committedHead.RevisionId,"C-27 lost-response retry replayed");s.PruneExpiredWitnesses(committedHead.Sequence+65);var expired=s.QueryIdempotency("c27-key");Expect(expired is {Success:false,Classification:"outcome_unknown"},"C-27 expired witness not outcome_unknown");var blocked=s.CommitTransaction(retryTx,h.RevisionId,"c27-key");Expect(blocked is {Success:false,Classification:"outcome_unknown"},"C-27 expired key replayed");var now=Snap(f.Path);Pass("C-27","successful commit with lost response","same idempotency retry then witness expiry","original result then outcome_unknown; no replay","committed_known then outcome_unknown",old,now,[target],"native","lost_response_idempotency_expiry",new{retry="committed_known",expired="outcome_unknown",replay_after_expiry=0});
    }

    private void Case28()
    {
        var f=Fresh("c28");var old=Snap(f.Path);Guid target;TransactionResult commit;using(var s=NativeDocumentSession.Open(f.Path,true)){var st=s.LoadState();target=Obj(st,o=>o.Type=="text_block"&&o.Role=="body").Id;var tx=s.BeginTransaction();tx.SetObjectProperty(target,"c28",1);commit=s.CommitTransaction(tx,s.ReadHead().RevisionId,"C-28");Expect(commit.Success&&commit.Delta is not null,"C-28 semantic commit/delta failed");Expect(commit.Delta!.ChangedObjects.Contains(target),"C-28 committed target absent from delta");ScorePositive("P-06","C-28",1,1,"semantic commit target present in exact delta before runtime loss");}string idx=Path.Combine(Work,"c28-runtime.db");using(var store=DndStore.Open(f.Path))using(var ri=new RuntimeIndex(idx))ri.RebuildFrom(store);File.Delete(idx);using(var store=DndStore.Open(f.Path))using(var ri=new RuntimeIndex(idx)){int rebuilt=ri.RebuildFrom(store);Expect(rebuilt>0,"C-28 runtime rebuild empty");var h=store.ReadHead();store.PruneExpiredWitnesses(h.Sequence+1);var d=store.ReadDeltas(0);Expect(d.ResyncRequired&&d.Classification=="resync_required","C-28 delta gap silent");}var now=Snap(f.Path);Pass("C-28","committed semantic head plus external runtime index","delete/rebuild runtime index and expire delta cursor","head valid; index rebuildable; cursor resync_required","resync_required",old,now,[target],"native","runtime_index_loss_and_delta_expiry",new{runtime_rebuilt=true,committed_delta_target_covered=true,expired_cursor="resync_required",semantic_head_valid=true});
    }

    private ProviderEnvironment PdfEnv(string manifestToken)
    {
        var fontFiles=new Dictionary<string,string>(StringComparer.Ordinal){{"Segoe UI",@"C:\Windows\Fonts\segoeui.ttf"},{"Segoe UI Bold",@"C:\Windows\Fonts\segoeuib.ttf"},{"Nirmala UI",@"C:\Windows\Fonts\Nirmala.ttc"},{"Yu Gothic",@"C:\Windows\Fonts\YuGothR.ttc"},{"Yu Gothic Bold",@"C:\Windows\Fonts\YuGothB.ttc"},{"Segoe UI Emoji",@"C:\Windows\Fonts\seguiemj.ttf"},{"Arial",@"C:\Windows\Fonts\arial.ttf"}};
        var digests=fontFiles.ToDictionary(k=>k.Key,v=>Sha(v.Value),StringComparer.Ordinal);digests["qualification-manifest"]=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(manifestToken))).ToLowerInvariant();
        var config=new Dictionary<string,string>(StringComparer.Ordinal){{"pdf_standard","PDF/UA-1"},{"a11y_extras","enabled"},{"paper","US Letter"},{"font_path",@"C:\Windows\Fonts"}};
        return new("Typst","0.15.1 (2d99e029)","en-US","Typst 0.15.1 bundled hyphenation",digests,config);
    }
    private ProviderEnvironment HtmlEnv()=>new("DOCSeye HTML","1","en-US","browser CSS line breaking",new Dictionary<string,string>(),new Dictionary<string,string>{{"mode","continuous accessible HTML"}});
    private (string Typst,string Vera,string Java,string Figure) RenderTools()=>
        (Path.Combine(Repo,".tools","typst","typst-x86_64-pc-windows-msvc","typst.exe"),Path.Combine(Repo,".tools","verapdf","verapdf.bat"),Path.Combine(Repo,".tools","java","jdk-25.0.4+7-jre"),Path.Combine(Repo,"tests","render","semantic-figure.svg"));

    private void Case29()
    {
        var f=Fresh("c29");var old=Snap(f.Path);using var s=NativeDocumentSession.Open(f.Path,true);var h0=s.ReadHead();var st0=s.LoadState();Guid body=Obj(st0,o=>o.Type=="text_block"&&o.Role=="body"&&Text(o).Contains("Arabic logical text",StringComparison.Ordinal)).Id,field=st0.Objects.Values.First(o=>!o.Retired&&o.Type=="field"&&Equals(o.Data.GetValueOrDefault("class"),"page_count")).Id,table=st0.Objects.Values.First(o=>!o.Retired&&o.Type=="table"&&Convert.ToInt32(o.Data.GetValueOrDefault("rows")??0)==4).Id,note=st0.Objects.Values.First(o=>!o.Retired&&o.Type=="note"&&o.Role=="footnote").Id;Guid headerFlow=st0.Objects.Values.First(o=>!o.Retired&&o.Type=="flow"&&o.Role=="header").Id,footerFlow=st0.Objects.Values.First(o=>!o.Retired&&o.Type=="flow"&&o.Role=="footer").Id,headerText=st0.Objects.Values.First(o=>!o.Retired&&o.Type=="text_block"&&o.ParentId==headerFlow).Id,footerText=st0.Objects.Values.First(o=>!o.Retired&&o.Type=="text_block"&&o.ParentId==footerFlow).Id;var ids=new[]{table,note,headerText,footerText,field};var tools=RenderTools();var provider=new TypstPdfProvider();var env=PdfEnv("c29-font-manifest");var basePdf=provider.Render(st0,h0,Path.Combine(Work,"c29-base-render"),ids,env,tools.Typst,tools.Vera,tools.Java,tools.Figure);
        var tx=s.BeginTransaction();int bodyEnd=UnicodeText.ScalarCount(Text(tx.State.Objects[body]));tx.InsertText(body,bodyEnd,string.Concat(Enumerable.Repeat(" \\u0641\\u0642\\u0631\\u0629 \\u0625\\u0636\\u0627\\u0641\\u064a\\u0629 \\u0644\\u0636\\u063a\\u0637 \\u0625\\u0639\\u0627\\u062f\\u0629 \\u0627\\u0644\\u062a\\u062f\\u0641\\u0642.",220)),true);tx.AddLayoutInvalidation("page-count-field");var r=s.CommitTransaction(tx,h0.RevisionId,"C-29");Expect(r.Success&&r.Delta is not null,"C-29 early edit failed");var st1=s.LoadState();var h1=s.ReadHead();var finalPdf=provider.Render(st1,h1,Path.Combine(Work,"c29-final-render"),ids,env,tools.Typst,tools.Vera,tools.Java,tools.Figure);bool tableReflow=basePdf.Mapping[table].Page!=finalPdf.Mapping[table].Page||basePdf.Mapping[table].X!=finalPdf.Mapping[table].X||basePdf.Mapping[table].Y!=finalPdf.Mapping[table].Y;bool noteReflow=basePdf.Mapping[note].Page!=finalPdf.Mapping[note].Page||basePdf.Mapping[note].X!=finalPdf.Mapping[note].X||basePdf.Mapping[note].Y!=finalPdf.Mapping[note].Y;bool pageCountChanged=basePdf.Mapping[headerText].Occurrences!=finalPdf.Mapping[headerText].Occurrences;bool pageFieldMapped=finalPdf.Mapping.ContainsKey(field);Expect(tableReflow&&noteReflow&&pageCountChanged&&pageFieldMapped,"C-29 required later-page/table/note/page-field reflow not observed");Expect(finalPdf.LayoutRevision.SemanticRevisionId==h1.RevisionId&&finalPdf.LayoutRevision.SemanticRoot==Convert.ToHexString(h1.SemanticRoot).ToLowerInvariant(),"C-29 render/source mismatch");Expect(st1.Objects.ContainsKey(body)&&st1.Objects.ContainsKey(table)&&st1.Objects.ContainsKey(note)&&st1.Objects.ContainsKey(field),"C-29 semantic identities drifted");var now=Snap(f.Path);Pass("C-29","paginated N-001 with page-count field","large early semantic edit changes all later pagination","new LayoutRevision; semantic IDs stable; table/note/page-count reflow exact","qualified paginated reflow observed",old,now,[body,table,note,field,headerText,footerText],"Typst PDF/UA-1","early_edit_pagination_invalidation",new{layout_before=basePdf.LayoutRevision.LayoutRevisionId,layout_after=finalPdf.LayoutRevision.LayoutRevisionId,base_pages=basePdf.Mapping[headerText].Occurrences,final_pages=finalPdf.Mapping[headerText].Occurrences,table_reflow=tableReflow,footnote_reflow=noteReflow,page_count_changed=pageCountChanged,page_field_mapped=pageFieldMapped,semantic_ids_stable=true,pdf_ua_1=true});
    }

    private void Case30()
    {
        var f=Fresh("c30");var old=Snap(f.Path);using var store=DndStore.Open(f.Path);var st=store.LoadState();var h=store.ReadHead();var ids=new[]{"Arabic logical text","Japanese CJK","Devanagari","Decomposed sequence","Emoji ZWJ"}.Select(x=>Obj(st,o=>o.Type=="text_block"&&o.Role=="body"&&Text(o).Contains(x,StringComparison.Ordinal)).Id).ToArray();var before=ids.ToDictionary(id=>id,id=>Text(st.Objects[id]));var tools=RenderTools();var provider=new TypstPdfProvider();var envA=PdfEnv("font-manifest-a");var envB=PdfEnv("font-manifest-b");var warnings=LayoutQualification.RequalificationWarnings(envA,envB);var a=provider.Render(st,h,Path.Combine(Work,"c30-a"),ids,envA,tools.Typst,tools.Vera,tools.Java,tools.Figure);var b=provider.Render(st,h,Path.Combine(Work,"c30-b"),ids,envB,tools.Typst,tools.Vera,tools.Java,tools.Figure);Expect(a.LayoutRevision.LayoutRevisionId!=b.LayoutRevision.LayoutRevisionId,"C-30 font manifest change did not alter layout qualification");Expect(ids.All(id=>a.Mapping.ContainsKey(id)&&b.Mapping.ContainsKey(id)),"C-30 script mapping incomplete");Expect(warnings.Contains("font_manifest_changed_requires_requalification",StringComparer.Ordinal),"C-30 requalification warning not reported");Expect(ids.All(id=>Text(st.Objects[id])==before[id]),"C-30 logical text changed during render");var now=Snap(f.Path);Pass("C-30","multilingual fixture under pinned paginated provider","change allowed font manifest; shape Arabic/CJK/Indic/combining/emoji","distinct LayoutRevision, provider warning, mapped scripts, logical text exact","two qualified PDF/UA renders with explicit requalification warning",old,now,ids,"Typst PDF/UA-1","font_manifest_shape_change",new{layout_a=a.LayoutRevision.LayoutRevisionId,layout_b=b.LayoutRevision.LayoutRevisionId,capability_warnings=warnings,mapped_scripts=ids.Length,logical_text_unchanged=true,pdf_ua_1=true});
    }

    private void Case31()
    {
        var f=Fresh("c31");var old=Snap(f.Path);using var s=NativeDocumentSession.Open(f.Path,true);var st=s.LoadState();Guid nestedTable=st.Objects.Values.First(o=>!o.Retired&&o.Type=="table"&&o.ParentId is Guid p&&st.Objects.TryGetValue(p,out var parent)&&parent.Type=="table_cell").Id,note=st.Objects.Values.First(o=>!o.Retired&&o.Type=="note"&&o.Role=="footnote").Id;Expect(!st.Extensions.Values.Any(e=>e.CoverageKind==ExtensionCoverageKind.TopologyRegion&&e.TargetId==nestedTable),"C-31 selected table is topology-extension covered");var tx=s.BeginTransaction();int added=0;for(int row=2;row<18;row++){tx.InsertTableRow(nestedTable,row,[$"edge-pressure-{row}-a",$"edge-pressure-{row}-b"]);added++;}tx.SetObjectProperty(nestedTable,"rows",18,true,"table_row_count");var r=s.CommitTransaction(tx,s.ReadHead().RevisionId,"C-31");Expect(r.Success,"C-31 semantic table growth failed: "+r.Classification);var end=s.LoadState();Expect(end.Objects.ContainsKey(nestedTable)&&end.Objects.ContainsKey(note)&&Convert.ToInt32(end.Objects[nestedTable].Data["rows"])==18,"C-31 semantic table/note postconditions failed");var html=new HtmlProvider();string output=Path.Combine(Work,"c31.html");var rendered=html.Render(end,s.ReadHead(),output,[nestedTable,note],HtmlEnv());var validation=RenderValidation.ValidateHtml(end,s.ReadHead(),output,[nestedTable,note]);Expect(validation.Valid&&rendered.Mapping.ContainsKey(nestedTable)&&rendered.Mapping.ContainsKey(note),"C-31 continuous provider failed semantic/accessibility projection");string classification="provider_limitation_continuous_html_no_paginated_table_footnote_relocation";var now=Snap(f.Path);Pass("C-31","nested table and footnote under layout pressure","commit 16-row growth requiring paginated table split/repeat-header and footnote relocation","qualified deterministic layout or explicit provider limitation; semantic IDs preserved",classification,old,now,[nestedTable,note],"continuous accessible HTML","table_growth_near_footnote_page_edge",new{semantic_commit=true,rows_added=added,semantic_ids_stable=true,html_mapping=true,html_accessibility_validation=validation.Classification,provider_limitation="continuous HTML has no paginated table-split/repeat-header/footnote-relocation contract",classification,silent_claim=false});
    }

    private void Case32()
    {
        var f=Fresh("c32");var old=Snap(f.Path);using var store=DndStore.Open(f.Path);var st=store.LoadState();var h=store.ReadHead();var provider=new HtmlProvider();var env=HtmlEnv();var required=f.Manifest.Objects.Where(o=>o.RequiredRenderMapping).Select(o=>Guid.Parse(o.Id)).ToArray();string dir=Path.Combine(Work,"c32-render");Directory.CreateDirectory(dir);string validPath=Path.Combine(dir,"valid.html");var valid=provider.Render(st,h,validPath,required,env);var validCheck=RenderValidation.ValidateHtml(st,h,validPath,required);int mapped=required.Count(valid.Mapping.ContainsKey);Expect(validCheck.Valid&&mapped==required.Length,"C-32 valid full required mapping/accessibility baseline failed");ScorePositive("P-07","C-32",mapped,required.Length,"all N-001 fixture objects marked RequiredRenderMapping have exact HTML source regions");
        bool stale=false;try{var bad=h with{RevisionId=Ids.NewV4()};provider.Render(st,bad,Path.Combine(dir,"stale.html"),required,env);}catch(InvalidOperationException ex)when(ex.Message=="semantic_head_mismatch"){stale=true;}Expect(stale,"C-32 stale render request not refused");
        string html=File.ReadAllText(validPath);Guid removedId=required.First();string marker="data-docseye-object-id=\""+Ids.Lower(removedId)+"\"";Expect(html.Contains(marker,StringComparison.Ordinal),"C-32 selected mapping marker absent");string missingPath=Path.Combine(dir,"missing-map.html");File.WriteAllText(missingPath,html.Replace(marker,"data-docseye-object-id=\"removed\"",StringComparison.Ordinal),new UTF8Encoding(false));var missing=RenderValidation.ValidateHtml(st,h,missingPath,required);Expect(!missing.Valid&&missing.Classification=="required_render_mapping_missing","C-32 removed required mapping passed validation");
        string inaccessiblePath=Path.Combine(dir,"inaccessible.html");File.WriteAllText(inaccessiblePath,html.Replace("aria-label=\"","data-removed-aria=\"",StringComparison.Ordinal),new UTF8Encoding(false));var inaccessible=RenderValidation.ValidateHtml(st,h,inaccessiblePath,required);Expect(!inaccessible.Valid&&inaccessible.Classification=="accessibility_validation_failed","C-32 inaccessible provider output passed validation");var now=Snap(f.Path);Pass("C-32","valid semantic/layout revision plus full required fixture mapping","stale render request, remove one required source map, then remove figure accessible names","mismatch refused; required mapping and accessibility validation fail","all three provider success gates enforced",old,now,required.Append(removedId),"continuous accessible HTML","stale_render_mapping_and_accessibility_injection",new{required_mapping_numerator=mapped,required_mapping_denominator=required.Length,valid_baseline=validCheck.Classification,stale_render="semantic_head_mismatch",missing_source_map=missing.Classification,accessibility=inaccessible.Classification,provider_success_claim_after_failed_validation=false});
    }
}
