using System.Security.Cryptography;
using System.Text;
using DOCSeye.Core;
using DOCSeye.Providers;
using DOCSeye.Storage.Sqlite;

public sealed partial class CHarness
{
    public void RunAnchorExtensionCases()=>RunAll();
    private void RunAll(){Case12();Case13();Case14();Case15();Case16();Case17();Case18();Case19();Case20();Case21();Case22();Case23();}

    private void Case12()
    {
        var f=Fresh("c12");var old=Snap(f.Path);SemanticState baseState;Guid id;using(var s=NativeDocumentSession.Open(f.Path,true)){baseState=s.LoadState();id=Obj(baseState,o=>o.Type=="text_block"&&o.Role=="body"&&Text(o).Contains("An early edit here",StringComparison.Ordinal)).Id;}
        var vectors=new List<Dictionary<string,object?>>();string[] kinds=["comment","style","suggestion","named_range"];
        foreach(string kind in kinds)
        {
            foreach(var v in new[]{(edge:"start",aff:EdgeAffinity.IncludeAtEdge,expected:5),(edge:"start",aff:EdgeAffinity.ExcludeAtEdge,expected:6),(edge:"end",aff:EdgeAffinity.IncludeAtEdge,expected:16),(edge:"end",aff:EdgeAffinity.ExcludeAtEdge,expected:15)})
            {
                var tx=new SemanticTransactionBuilder(baseState);EdgeAffinity sa=v.edge=="start"?v.aff:EdgeAffinity.ExcludeAtEdge,ea=v.edge=="end"?v.aff:EdgeAffinity.ExcludeAtEdge;Guid rid=tx.RetainRange(id,5,15,kind,sa,ea);tx.InsertText(id,v.edge=="start"?5:15,"X",true);var rr=tx.State.Ranges[rid];int actual=v.edge=="start"?tx.State.Boundaries[rr.StartBoundaryId].ScalarOffset:tx.State.Boundaries[rr.EndBoundaryId].ScalarOffset;Expect(actual==v.expected,$"C-12 {kind}/{v.edge}/{v.aff} => {actual}, expected {v.expected}");vectors.Add(new(StringComparer.Ordinal){{"kind",kind},{"edge",v.edge},{"affinity",v.aff.ToString()},{"actual",actual},{"expected",v.expected}});
            }
        }
        foreach(var pnt in new[]{(aff:EdgeAffinity.BeforeInsertion,expected:10),(aff:EdgeAffinity.AfterInsertion,expected:11)})
        {
            var tx=new SemanticTransactionBuilder(baseState);Guid rid=tx.RetainRange(id,10,10,"named_point_anchor",pnt.aff,pnt.aff,false);tx.InsertText(id,10,"X",true);Guid bid=tx.State.Ranges[rid].StartBoundaryId;int actual=tx.State.Boundaries[bid].ScalarOffset;Expect(actual==pnt.expected,$"C-12 point {pnt.aff} => {actual}");vectors.Add(new(StringComparer.Ordinal){{"kind","named_point_anchor"},{"edge","point"},{"affinity",pnt.aff.ToString()},{"actual",actual},{"expected",pnt.expected}});
        }
        using(var s=NativeDocumentSession.Open(f.Path,true)){var tx=s.BeginTransaction();Guid rid=tx.RetainRange(id,5,15,"comment",EdgeAffinity.IncludeAtEdge,EdgeAffinity.ExcludeAtEdge);tx.InsertText(id,5,"X",true);var r=s.CommitTransaction(tx,s.ReadHead().RevisionId,"C-12");Expect(r.Success,"C-12 representative commit failed: "+r.Classification);Expect(s.LoadState().Ranges[rid].State=="live","C-12 representative range lost");}
        var now=Snap(f.Path);Pass("C-12","comment/style/suggestion/named-range anchors plus point anchors","insert at every start/end policy edge and before/after point","18/18 logical inclusion vectors exact","18/18 exact",old,now,[id],"native","retained_boundary_edge_matrix",new{vectors,total=vectors.Count,passed=vectors.Count});
    }

    private void Case13()
    {
        var f=Fresh("c13");var old=Snap(f.Path);using var s=NativeDocumentSession.Open(f.Path,true);Guid id=Obj(s.LoadState(),o=>o.Type=="text_block"&&o.Role=="body"&&Text(o).Contains("An early edit here",StringComparison.Ordinal)).Id;var tx=s.BeginTransaction();Guid a=tx.RetainRange(id,4,16,"comment",EdgeAffinity.IncludeAtEdge,EdgeAffinity.ExcludeAtEdge),b=tx.RetainRange(id,4,20,"style",EdgeAffinity.ExcludeAtEdge,EdgeAffinity.IncludeAtEdge);var ar=tx.State.Ranges[a];var br=tx.State.Ranges[b];Guid asb=ar.StartBoundaryId,dsb=br.StartBoundaryId;EdgeAffinity otherAffinity=tx.State.Boundaries[dsb].Affinity;Expect(asb!=dsb&&tx.State.Boundaries[asb].ScalarOffset==tx.State.Boundaries[dsb].ScalarOffset,"C-13 co-located boundaries aliased");tx.ReleaseRange(a);tx.InsertText(id,4,"Q",true);Expect(tx.State.Ranges[a].State=="destroyed"&&tx.State.Ranges[b].State=="live","C-13 range state leaked");Expect(tx.State.Boundaries[dsb].State==AnchorState.Live&&tx.State.Boundaries[dsb].Affinity==otherAffinity&&tx.State.Boundaries[dsb].ScalarOffset==5,"C-13 independent boundary policy mutated");var r=s.CommitTransaction(tx,s.ReadHead().RevisionId,"C-13");Expect(r.Success,"C-13 commit failed: "+r.Classification);var now=Snap(f.Path);Pass("C-13","overlapping ranges with co-located independent boundaries","release one range and insert at shared position","other identities/policies unaffected","independent boundary identity/policy preserved",old,now,[id,a,b,asb,dsb],"native","overlap_release_shared_position_insert",new{released=Ids.Lower(a),unaffected=Ids.Lower(b),co_located_distinct=true,unaffected_start=5});
    }

    private void Case14()
    {
        var f=Fresh("c14");var old=Snap(f.Path);using var s=NativeDocumentSession.Open(f.Path,true);var st=s.LoadState();var matches=st.Objects.Values.Where(o=>!o.Retired&&o.Type=="text_block"&&o.Role=="body"&&Text(o).Contains("correspondence pressure phrase",StringComparison.Ordinal)).OrderBy(o=>Ids.Lower(o.Id),StringComparer.Ordinal).ToArray();Expect(matches.Length>=2,"C-14 repeated quote fixture missing");Guid id=matches[0].Id,decoy=matches[1].Id;string decoyBefore=Text(matches[1]);var tx=s.BeginTransaction();string before=Text(tx.State.Objects[id]);int at=ScalarIndex(before,"correspondence pressure phrase");Guid range=tx.RetainRange(id,at,at+UnicodeText.ScalarCount("correspondence pressure phrase"),"named_range");var rr=tx.State.Ranges[range];Guid sb=rr.StartBoundaryId,eb=rr.EndBoundaryId;tx.DeleteText(id,at+5,5,true);string expected=UnicodeText.Delete(before,at+5,5,true);tx.ReplaceText(id,at+2,2,"XY",true);expected=UnicodeText.Insert(UnicodeText.Delete(expected,at+2,2,true),at+2,"XY",true);Expect(Text(tx.State.Objects[id])==expected,"C-14 exact replacement text mismatch");Expect(tx.State.Boundaries[sb].Id==sb&&tx.State.Boundaries[eb].Id==eb,"C-14 boundaries reminted");Expect(Text(tx.State.Objects[decoy])==decoyBefore,"C-14 quote-like decoy mutated");var r=s.CommitTransaction(tx,s.ReadHead().RevisionId,"C-14");Expect(r.Success,"C-14 commit failed: "+r.Classification);var end=s.LoadState();Expect(Text(end.Objects[decoy])==decoyBefore,"C-14 persisted decoy mutation");var now=Snap(f.Path);Pass("C-14","retained target plus repeated quote-like decoy","partial delete plus typed replacement","exact shrink/replacement; no quote search","exact target-only mapping",old,now,[id,decoy,range,sb,eb],"native","partial_delete_typed_replace",new{boundary_ids_preserved=true,decoy_unchanged=true,quote_rebinds=0,final_text_exact=true});
    }

    private void Case15()
    {
        var f=Fresh("c15");var old=Snap(f.Path);SemanticState st;using(var s=NativeDocumentSession.Open(f.Path,true))st=s.LoadState();Guid root=st.Objects.Values.First(o=>!o.Retired&&o.Type=="document").Id;var lifecycle=new List<Dictionary<string,object?>>();
        foreach(var v in new[]{(kind:"comment",state:"orphaned",retire:"retained_boundary_requires_typed_retirement"),(kind:"style",state:"destroyed",retire:"retired"),(kind:"named_range",state:"collapsed",retire:"retained_boundary_requires_typed_retirement"),(kind:"field_reference",state:"unresolved",retire:"retained_boundary_requires_typed_retirement")})
        {
            var tx=new SemanticTransactionBuilder(st);Guid leaf=tx.CreateObject("text_block",root,"body",new(StringComparer.Ordinal){{"text","controlled lifecycle leaf text"}});Guid rid=tx.RetainRange(leaf,2,10,v.kind);tx.DeleteText(leaf,2,8,true);string state=tx.State.Ranges[rid].State;Expect(state==v.state,$"C-15 {v.kind} state {state} != {v.state}");string retire="retired";try{tx.RetireObject(leaf);}catch(SemanticRefusalException ex){retire=ex.Code;}Expect(retire==v.retire,$"C-15 {v.kind} owner retirement {retire} != {v.retire}");lifecycle.Add(new(StringComparer.Ordinal){{"kind",v.kind},{"range_state",state},{"owner_retirement",retire}});
        }
        var req=st.Extensions.Values.Single(x=>x.Required&&x.CoverageKind==ExtensionCoverageKind.TextInterval);int rs=st.Boundaries[req.StartBoundaryId!.Value].ScalarOffset,re=st.Boundaries[req.EndBoundaryId!.Value].ScalarOffset;string required="";try{var tx=new SemanticTransactionBuilder(st);tx.DeleteText(req.TargetId!.Value,rs,Math.Max(1,re-rs),true);}catch(SemanticRefusalException ex){required=ex.Code;}Expect(required=="blocked_required_extension","C-15 required extension deletion did not refuse");
        using(var s=NativeDocumentSession.Open(f.Path,true)){var tx=s.BeginTransaction();Guid leaf=tx.CreateObject("text_block",root,"body",new(StringComparer.Ordinal){{"text","persisted lifecycle representative"}});Guid rid=tx.RetainRange(leaf,2,10,"comment");tx.DeleteText(leaf,2,8,true);Expect(tx.State.Ranges[rid].State=="orphaned","C-15 representative not orphaned");tx.ReleaseRange(rid);tx.RetireObject(leaf);var r=s.CommitTransaction(tx,s.ReadHead().RevisionId,"C-15");Expect(r.Success,"C-15 commit failed: "+r.Classification);}
        var now=Snap(f.Path);Pass("C-15","comment/style/reference/required-extension targets","delete complete range then owner block","typed orphaned/destroyed/collapsed/unresolved/refused","all typed lifecycle vectors exact",old,now,[req.ExtensionId,req.TargetId!.Value],"native","complete_range_delete_and_owner_retire",new{lifecycle,required_extension=required});
    }

    private void Case16()
    {
        var f=Fresh("c16");var old=Snap(f.Path);using var s=NativeDocumentSession.Open(f.Path,true);var st=s.LoadState();Guid root=st.Objects.Values.First(o=>!o.Retired&&o.Type=="document").Id;var tx=s.BeginTransaction();Guid id=tx.CreateObject("text_block",root,"body",new(StringComparer.Ordinal){{"text","controlled split leaf with enough scalar content for retained range"}});Guid range=tx.RetainRange(id,3,20,"named_range",allowMultiInterval:true);var bounds=tx.State.Ranges[range].EffectiveIntervals.SelectMany(x=>new[]{x.StartBoundaryId,x.EndBoundaryId}).Distinct().ToArray();var split=tx.SplitText(id,10);Expect(tx.State.Retired[id].Resolution==RetiredResolution.Split&&tx.State.Retired[id].Successors.ToHashSet().SetEquals([split.Left,split.Right]),"C-16 split witness wrong");Expect(bounds.All(tx.State.Boundaries.ContainsKey),"C-16 boundary identity lost");var owners=bounds.Select(x=>tx.State.Boundaries[x].OwnerId).Distinct().ToArray();Expect(owners.ToHashSet().SetEquals([split.Left,split.Right])&&tx.State.Ranges[range].AllowMultiInterval,"C-16 cross-split range topology wrong");var r=s.CommitTransaction(tx,s.ReadHead().RevisionId,"C-16");Expect(r.Success,"C-16 commit failed: "+r.Classification);var now=Snap(f.Path);Pass("C-16","range crossing text split","split inside retained range","source retired split_into; successors new; boundary IDs retained","typed split with exact boundary ownership",old,now,new[]{id,split.Left,split.Right,range}.Concat(bounds),"native","anchored_text_split",new{retirement="split",successors=2,boundary_ids_preserved=true,boundary_owner_count=owners.Length,allow_multi_interval=true});
    }

    private void Case17()
    {
        var f=Fresh("c17");var old=Snap(f.Path);using var s=NativeDocumentSession.Open(f.Path,true);var st=s.LoadState();Guid root=st.Objects.Values.First(o=>!o.Retired&&o.Type=="document").Id,targetParent=st.Objects.Values.First(o=>!o.Retired&&o.Type=="section").Id;var tx=s.BeginTransaction();Guid left=tx.CreateObject("text_block",root,"body",new(StringComparer.Ordinal){{"text","merge-left-anchored"}}),right=tx.CreateObject("text_block",root,"body",new(StringComparer.Ordinal){{"text","merge-right-anchored"}});Guid lr=tx.RetainRange(left,1,8,"comment"),rr=tx.RetainRange(right,1,9,"named_range");Guid[] boundaryIds=[..tx.State.Ranges[lr].EffectiveIntervals.Concat(tx.State.Ranges[rr].EffectiveIntervals).SelectMany(x=>new[]{x.StartBoundaryId,x.EndBoundaryId}).Distinct()];Guid merged=tx.MergeText(left,right);Expect(tx.State.Retired[left].Resolution==RetiredResolution.Merged&&tx.State.Retired[right].Resolution==RetiredResolution.Merged,"C-17 merge witnesses missing");Expect(tx.State.Retired[left].Successors.Single()==merged&&tx.State.Retired[right].Successors.Single()==merged,"C-17 merge successor wrong");tx.MoveObject(merged,targetParent,0);Expect(tx.State.Objects[merged].ParentId==targetParent&&boundaryIds.All(b=>tx.State.Boundaries[b].OwnerId==merged),"C-17 post-merge move/boundary mapping wrong");var r=s.CommitTransaction(tx,s.ReadHead().RevisionId,"C-17-merge-move");Expect(r.Success,"C-17 merge/move commit failed: "+r.Classification);Guid committedMerged=s.LoadState().Objects[merged].Id;var gc=s.BeginTransaction();int collected=gc.GarbageCollectRetiredWitnesses(long.MaxValue-1);var g=s.CommitTransaction(gc,s.ReadHead().RevisionId,"C-17-gc");Expect(g.Success&&collected>=2,"C-17 lineage GC failed");var end=s.LoadState();Expect(end.Objects[merged].Id==committedMerged&&end.Objects[merged].ParentId==targetParent,"C-17 merged result identity drifted");Expect(end.Retired[left].Resolution==RetiredResolution.UnknownRetired&&end.Retired[right].Resolution==RetiredResolution.UnknownRetired,"C-17 source lineage did not become unknown_retired");var now=Snap(f.Path);Pass("C-17","two anchored text blocks","merge, move merged result, then lineage GC","sources merged_into result; result ID stable through move; later unknown_retired only","exact merge/move/GC lifecycle",old,now,new[]{left,right,merged,lr,rr}.Concat(boundaryIds),"native","merge_move_lineage_gc",new{merged_result=Ids.Lower(merged),boundary_ids_preserved=true,parent_after_move=Ids.Lower(targetParent),post_gc="unknown_retired",collected});
    }

    private void Case18()
    {
        var f=Fresh("c18");var old=Snap(f.Path);using var s=NativeDocumentSession.Open(f.Path,true);var st=s.LoadState();Guid dec=Obj(st,o=>o.Type=="text_block"&&Text(o).Contains("Decomposed sequence",StringComparison.Ordinal)).Id,emoji=Obj(st,o=>o.Type=="text_block"&&Text(o).Contains("Emoji ZWJ",StringComparison.Ordinal)).Id,bidi=Obj(st,o=>o.Type=="text_block"&&Text(o).Contains("Mixed bidi",StringComparison.Ordinal)).Id,arabic=Obj(st,o=>o.Type=="text_block"&&Text(o).Contains("Arabic logical text",StringComparison.Ordinal)).Id;var head=s.ReadHead();var staleHandle=new PortableWriteHandle(head.FamilyId,head.BranchId,arabic,head.RevisionId);var tx=s.BeginTransaction();
        string emojiBefore=Text(tx.State.Objects[emoji]);var runes=emojiBefore.EnumerateRunes().ToArray();int zwj=Array.FindIndex(runes,r=>r.Value==0x200D);Expect(zwj>0,"C-18 ZWJ fixture missing");var gb=UnicodeText.GraphemeScalarBoundaries(emojiBefore);int clusterStart=gb.Last(x=>x<zwj),clusterEnd=gb.First(x=>x>zwj);string interior="";try{tx.DeleteText(emoji,zwj,1,true);}catch(InvalidOperationException ex){interior=ex.Message;}Expect(interior=="invalid_grapheme_boundary","C-18 grapheme-interior edit not refused");tx.ReplaceText(emoji,clusterStart,clusterEnd-clusterStart,"[emoji]",true);string emojiExpected=UnicodeText.Insert(UnicodeText.Delete(emojiBefore,clusterStart,clusterEnd-clusterStart,true),clusterStart,"[emoji]",true);
        string decBefore=Text(tx.State.Objects[dec]);int cafe=ScalarIndex(decBefore,"cafe\u0301"),afterCafe=cafe+UnicodeText.ScalarCount("cafe\u0301");Expect(UnicodeText.IsGraphemeBoundary(decBefore,afterCafe),"C-18 decomposed cluster end not boundary");tx.InsertText(dec,afterCafe,"!",true);string decExpected=UnicodeText.Insert(decBefore,afterCafe,"!",true);
        string bidiBefore=Text(tx.State.Objects[bidi]);int english=ScalarIndex(bidiBefore,"English");tx.ReplaceText(bidi,english,7,"Logical",true);string bidiExpected=UnicodeText.Insert(UnicodeText.Delete(bidiBefore,english,7,true),english,"Logical",true);
        string arBefore=Text(tx.State.Objects[arabic]);int arAt=UnicodeText.GraphemeScalarBoundaries(arBefore).Skip(1).First();tx.InsertText(arabic,arAt,"A",true);string arExpected=UnicodeText.Insert(arBefore,arAt,"A",true);
        var r=s.CommitTransaction(tx,head.RevisionId,"C-18");Expect(r.Success,"C-18 Unicode commit failed: "+r.Classification);var end=s.LoadState();Expect(Text(end.Objects[emoji])==emojiExpected&&Text(end.Objects[dec])==decExpected&&Text(end.Objects[bidi])==bidiExpected&&Text(end.Objects[arabic])==arExpected,"C-18 logical text mismatch/normalization drift");string afterCommit=Sha(f.Path);var stale=s.CommitObjectData(staleHandle,Change(st.Objects[arabic],"text","must-not-write"),"C-18-stale");Expect(!stale.Success&&stale.Classification=="stale_revision"&&Sha(f.Path)==afterCommit,"C-18 stale external write was not exact refusal");var now=Snap(f.Path);Pass("C-18","decomposed combining, emoji/ZWJ, Arabic, mixed bidi","valid scalar/grapheme edits plus interior and stale attempts","Unicode-safe exact mapping or explicit stale/grapheme refusal","exact logical text; invalid_grapheme_boundary; stale_revision",old,now,[dec,emoji,bidi,arabic],"native","unicode_grapheme_and_stale",new{grapheme_interior=interior,stale=stale.Classification,logical_text_exact=true,hidden_normalization=0});
    }

    private void Case19()
    {
        var f=Fresh("c19");var old=Snap(f.Path);SemanticState st;using(var s=NativeDocumentSession.Open(f.Path,true))st=s.LoadState();var tracked=st.Extensions.Values.Where(e=>!e.Required&&e.EditPolicy==ExtensionEditPolicy.Independent&&(e.CoverageKind==ExtensionCoverageKind.Object||e.CoverageKind==ExtensionCoverageKind.Property)).ToArray();Expect(tracked.Length>=2,"C-19 object/property optional extensions missing");var snapshots=tracked.ToDictionary(e=>e.ExtensionId,e=>new{Payload=e.ExactPayload.ToArray(),Digest=e.PayloadDigest.ToArray(),e.CoverageKind,e.TargetId,e.PropertyName,e.Required,e.Fallback});Guid target=st.Objects.Values.First(o=>!o.Retired&&o.Type=="text_block"&&tracked.All(e=>e.TargetId!=o.Id)).Id;using(var s=NativeDocumentSession.Open(f.Path,true)){var tx=s.BeginTransaction();tx.SetObjectProperty(target,"c19_disjoint",true);var r=s.CommitTransaction(tx,s.ReadHead().RevisionId,"C-19");Expect(r.Success,"C-19 commit failed: "+r.Classification);}using(var store=DndStore.Open(f.Path)){store.VacuumAndRebuildIndexes();store.RebuildMerkleCache();Expect(store.Validate(true).Writable,"C-19 record rewrite invalidated artifact");var end=store.LoadState();foreach(var e in tracked){var a=snapshots[e.ExtensionId];var z=end.Extensions[e.ExtensionId];Expect(z.ExactPayload.SequenceEqual(a.Payload)&&z.PayloadDigest.SequenceEqual(a.Digest)&&z.CoverageKind==a.CoverageKind&&z.TargetId==a.TargetId&&z.PropertyName==a.PropertyName&&z.Required==a.Required&&z.Fallback==a.Fallback,"C-19 extension field drift");}}var now=Snap(f.Path);Pass("C-19","optional object/property extensions","disjoint edit then physical/index record rewrite","payload/value/digest/coverage exact","all optional extension fields exact",old,now,tracked.Select(x=>x.ExtensionId).Append(target),"native","disjoint_edit_then_vacuum_reindex",new{extension_count=tracked.Length,payload_loss=0,coverage_escape=0,digest_drift=0});
    }

    private void Case20()
    {
        var f=Fresh("c20");var old=Snap(f.Path);using var s=NativeDocumentSession.Open(f.Path,true);var st=s.LoadState();Guid root=st.Objects.Values.First(o=>!o.Retired&&o.Type=="document").Id,newParent=st.Objects.Values.First(o=>!o.Retired&&o.Type=="section").Id;var setup=s.BeginTransaction();Guid target=setup.CreateObject("text_block",root,"body",new(StringComparer.Ordinal){{"text","c20 movable extension target"}});byte[] movePayload=Encoding.UTF8.GetBytes("c20-move"),genericPayload=Encoding.UTF8.GetBytes("c20-generic");Guid moveExt=Ids.NewV4(),genericExt=Ids.NewV4();setup.AddExtension(new(moveExt,"urn:c20:move","move",1,0,"bytes",movePayload,SHA256.HashData(movePayload),ExtensionCoverageKind.Object,target,null,null,null,ExtensionEditPolicy.MoveWithTarget,false,null));setup.AddExtension(new(genericExt,"urn:c20:generic","generic",1,0,"bytes",genericPayload,SHA256.HashData(genericPayload),ExtensionCoverageKind.Object,target,null,null,null,ExtensionEditPolicy.GenericTransform,false,null));var sr=s.CommitTransaction(setup,s.ReadHead().RevisionId,"C-20-setup");Expect(sr.Success,"C-20 setup failed: "+sr.Classification);
        var tx=s.BeginTransaction();tx.MoveObject(target,newParent,0);var map=Branching.PasteObjectSubgraph(tx.State,tx.State,target,null,false);Guid copiedTarget=map[target];Guid copiedMove=tx.CopyTransformableExtension(moveExt,map),copiedGeneric=tx.CopyTransformableExtension(genericExt,map);var r=s.CommitTransaction(tx,s.ReadHead().RevisionId,"C-20-move-copy");Expect(r.Success,"C-20 move/copy failed: "+r.Classification);var end=s.LoadState();Expect(end.Objects[target].ParentId==newParent&&copiedTarget!=target,"C-20 target move/copy wrong");Expect(end.Extensions[moveExt].TargetId==target&&end.Extensions[genericExt].TargetId==target,"C-20 original extension target drift");Expect(end.Extensions[copiedMove].TargetId==copiedTarget&&end.Extensions[copiedGeneric].TargetId==copiedTarget,"C-20 copied extension remap wrong");Expect(end.Extensions[copiedMove].ExactPayload.SequenceEqual(movePayload)&&end.Extensions[copiedGeneric].ExactPayload.SequenceEqual(genericPayload),"C-20 copied payload drift");var now=Snap(f.Path);Pass("C-20","move-with-target and generic-transform extensions","move original target; same-branch copy/remint; copy transformable extensions","original coverage follows stable target ID; copied coverage remapped to new occurrence","exact move/remap",old,now,[target,copiedTarget,moveExt,genericExt,copiedMove,copiedGeneric],"native","move_target_then_copy_remint",new{target_id_preserved_through_move=true,copied_target_reminted=true,extension_ids_reminted=true,payload_exact=true});
    }

    private void Case21()
    {
        var f=Fresh("c21");var old=Snap(f.Path);SemanticState st;using(var s=NativeDocumentSession.Open(f.Path,true))st=s.LoadState();var e=st.Extensions.Values.Single(x=>x.Required&&x.CoverageKind==ExtensionCoverageKind.TextInterval);int a=st.Boundaries[e.StartBoundaryId!.Value].ScalarOffset,b=st.Boundaries[e.EndBoundaryId!.Value].ScalarOffset;var classes=new List<string>();foreach(string op in new[]{"insert","delete"}){try{var tx=new SemanticTransactionBuilder(st);if(op=="insert")tx.InsertText(e.TargetId!.Value,(a+b)/2,"X",true);else tx.DeleteText(e.TargetId!.Value,a,Math.Max(1,b-a),true);}catch(SemanticRefusalException ex){classes.Add(ex.Code);}}Expect(classes.Count==2&&classes.All(x=>x=="blocked_required_extension"),"C-21 required interval refusal mismatch");var now=Snap(f.Path);Expect(old.Sha256==now.Sha256&&old.RevisionId==now.RevisionId,"C-21 blocked edit wrote state");using(var verify=DndStore.Open(f.Path)){var retained=verify.LoadState().Extensions[e.ExtensionId];Expect(retained.ExactPayload.SequenceEqual(e.ExactPayload)&&retained.PayloadDigest.SequenceEqual(e.PayloadDigest),"C-21 required extension payload changed despite refusal");}ScorePositive("P-05","C-21",1,1,"required text-interval extension payload and digest remained exact across refused intersecting edits");Pass("C-21","required text-interval extension","crossing insert/delete without capability","blocked_required_extension and zero commit","both vectors blocked_required_extension",old,now,[e.ExtensionId,e.TargetId!.Value],"native","required_text_interval_intersection",new{classifications=classes,writes=0});
    }

    private void Case22()
    {
        var f=Fresh("c22");var old=Snap(f.Path);SemanticState st;using(var s=NativeDocumentSession.Open(f.Path,true))st=s.LoadState();var e=st.Extensions.Values.Single(x=>x.CoverageKind==ExtensionCoverageKind.TopologyRegion);Guid table=e.TargetId!.Value;var policy=ExtensionPolicyEngine.Check(st,new("table_split_cell",table,TopologyMutation:true));Expect(policy.Allowed&&policy.RequiresTransform,"C-22 topology policy did not require transform");Guid merged=st.Objects.Values.First(o=>!o.Retired&&o.Type=="table_cell"&&o.ParentId==table&&Convert.ToInt32(o.Data.GetValueOrDefault("row_span")??1)>1).Id;Guid[] cells=[..st.Objects.Values.Where(o=>!o.Retired&&o.Type=="table_cell"&&o.ParentId==table).Take(2).Select(o=>o.Id)];var refusals=new List<string>();
        void Attempt(Action<SemanticTransactionBuilder> action){try{var tx=new SemanticTransactionBuilder(st);action(tx);throw new InvalidOperationException("C-22 topology edit unexpectedly succeeded");}catch(SemanticRefusalException ex){refusals.Add(ex.Code);}}
        Attempt(tx=>tx.SplitTableCell(table,merged,1,2));Attempt(tx=>tx.MergeTableCells(table,cells,0,0,1,2,"blocked merge"));Attempt(tx=>tx.InsertTableRow(table,1,["a","b","c","d"]));Expect(refusals.Count==3&&refusals.All(x=>x=="extension_transform_required"),"C-22 explicit topology refusal mismatch");Expect(Snap(f.Path).Sha256==old.Sha256,"C-22 refused topology vector wrote artifact");
        byte[] transformed=Encoding.UTF8.GetBytes("C-22 exact transformed opaque topology payload");IReadOnlyList<Guid> successors;using(var s=NativeDocumentSession.Open(f.Path,true)){var tx=s.BeginTransaction();tx.TransformExtension(e.ExtensionId,transformed);successors=tx.SplitTableCell(table,merged,1,2);var r=s.CommitTransaction(tx,s.ReadHead().RevisionId,"C-22-transformed");Expect(r.Success,"C-22 declared transform commit failed: "+r.Classification);var end=s.LoadState();Expect(end.Extensions[e.ExtensionId].ExactPayload.SequenceEqual(transformed)&&end.Extensions[e.ExtensionId].DigestValid,"C-22 transformed payload/digest drift");Expect(end.Retired[merged].Resolution==RetiredResolution.Split&&end.Retired[merged].Successors.SequenceEqual(successors),"C-22 topology successors wrong");}
        var now=Snap(f.Path);Pass("C-22","generic-transform topology extension over merged table","three topology edits without transform, then declared payload transform plus cell split","untransformed edits refused; transformed edit exact and writable","3x extension_transform_required then exact transformed commit",old,now,new[]{e.ExtensionId,table,merged}.Concat(successors),"native","topology_negative_matrix_then_declared_transform",new{requires_transform=true,negative_classifications=refusals,negative_writes=0,positive_transform=true,transformed_payload_sha256=Convert.ToHexString(SHA256.HashData(transformed)).ToLowerInvariant(),successors=successors.Select(Ids.Lower).ToArray()});
    }

    private void Case23()
    {
        var f=Fresh("c23");var old=Snap(f.Path);SemanticState st;using(var store=DndStore.Open(f.Path))st=store.LoadState();var req=st.Extensions.Values.Single(x=>x.Required);var opt=st.Extensions.Values.Single(x=>!x.Required&&x.Fallback is not null);var caps=ExtensionCapabilityPolicy.Assess(st);var reqCap=caps.Single(x=>x.ExtensionId==req.ExtensionId);var optCap=caps.Single(x=>x.ExtensionId==opt.ExtensionId);Expect(reqCap.State==CapabilityState.BlockedRequiredExtension&&reqCap.Classification=="blocked_required_extension","C-23 required capability classification wrong");Expect(optCap.State==CapabilityState.FallbackOnly&&optCap.Classification=="fallback_only"&&optCap.Fallback==opt.Fallback,"C-23 fallback classification wrong");string nativeBlock="";try{var tx=new SemanticTransactionBuilder(st);int a=st.Boundaries[req.StartBoundaryId!.Value].ScalarOffset;int b=st.Boundaries[req.EndBoundaryId!.Value].ScalarOffset;tx.InsertText(req.TargetId!.Value,(a+b)/2,"X",true);}catch(SemanticRefusalException ex){nativeBlock=ex.Code;}Expect(nativeBlock=="blocked_required_extension","C-23 native required capability did not block");string bad=Path.Combine(Work,"c23-corrupt.dnd");CopyArtifact(f.Path,bad);Sql(bad,$"UPDATE extensions SET payload=X'00' WHERE id=X'{Convert.ToHexString(Ids.RfcBytes(req.ExtensionId))}';");AssertInvalidNoWrite(bad,"invalid_extension",req.TargetId!.Value);var now=Snap(bad);Pass("C-23","optional fallback and required unknown extension","remove capability semantics and corrupt required payload","corrupt invalid/non-writable; required blocked; optional fallback explicitly labeled","invalid_extension + blocked_required_extension + fallback_only",old,now,[req.ExtensionId,opt.ExtensionId,req.TargetId!.Value],"native+capability-policy","corrupt_payload_and_missing_capability",new{corrupt="invalid_extension",required=reqCap.Classification,native_required=nativeBlock,optional=optCap.Classification,fallback=optCap.Fallback,provider_success_claim=false});
    }
}
