using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace DOCSeye.Fixtures;

public sealed record F001Manifest(string Sha256,long Length,IReadOnlyList<string> Features,IReadOnlyDictionary<string,string> EntrySha256);

public static class F001Generator
{
    public static readonly string[] RequiredFeatures =
    [
        "headings_styles","nested_restarted_numbering","merged_table","nested_table","comments_replies","tracked_insert","tracked_delete","tracked_move","tracked_style_change","metadata_field","cross_reference_field","page_field","text_content_control","enum_content_control","bookmarks_internal_refs","section_header_footer","footnote","endnote","figure_media","omml","custom_xml","alternate_content","unknown_mc","opaque_custom_part","inert_opaque_binary"
    ];

    public static F001Manifest Write(string path,string? manifestPath=null)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);if(File.Exists(path))File.Delete(path);
        var entries=BuildEntries();using(var fs=File.Create(path))using(var zip=new ZipArchive(fs,ZipArchiveMode.Create,false,Encoding.UTF8))foreach(var pair in entries){var e=zip.CreateEntry(pair.Key,CompressionLevel.NoCompression);e.LastWriteTime=new DateTimeOffset(2020,1,1,0,0,0,TimeSpan.Zero);using var s=e.Open();s.Write(pair.Value);}
        byte[] package=File.ReadAllBytes(path);var manifest=new F001Manifest(Convert.ToHexString(SHA256.HashData(package)).ToLowerInvariant(),package.LongLength,RequiredFeatures,entries.ToDictionary(k=>k.Key,v=>Convert.ToHexString(SHA256.HashData(v.Value)).ToLowerInvariant(),StringComparer.Ordinal));if(manifestPath is not null){Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(manifestPath))!);File.WriteAllText(manifestPath,JsonSerializer.Serialize(manifest,new JsonSerializerOptions{WriteIndented=true}),new UTF8Encoding(false));}return manifest;
    }

    public static IReadOnlyDictionary<string,byte[]> BuildEntries()
    {
        var d=new SortedDictionary<string,byte[]>(StringComparer.Ordinal);void X(string name,string xml)=>d[name]=Encoding.UTF8.GetBytes(xml.Replace("\r\n","\n"));
        X("[Content_Types].xml",Types);X("_rels/.rels",RootRels);X("docProps/app.xml",App);X("docProps/core.xml",Core);X("word/_rels/document.xml.rels",DocumentRels);X("word/comments.xml",Comments);X("word/commentsExtended.xml",CommentsExtended);X("word/document.xml",Document);X("word/endnotes.xml",Endnotes);X("word/footer1.xml",Footer);X("word/footnotes.xml",Footnotes);X("word/header1.xml",Header);X("word/numbering.xml",Numbering);X("word/settings.xml",Settings);X("word/styles.xml",Styles);X("customXml/item1.xml",CustomXml);X("customXml/itemProps1.xml",CustomXmlProps);X("customXml/_rels/item1.xml.rels",CustomXmlRels);X("word/custom/opaque.xml",OpaqueCustom);d["word/embeddings/opaque.bin"]=Encoding.ASCII.GetBytes("DOCSeye inert opaque binary fixture - never execute\0\x01\x02");d["word/media/image1.png"]=Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Z7xkAAAAASUVORK5CYII=");return d;
    }

    private const string Types="""<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Default Extension="bin" ContentType="application/octet-stream"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/><Override PartName="/word/comments.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml"/><Override PartName="/word/commentsExtended.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.commentsExtended+xml"/><Override PartName="/word/header1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/><Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/><Override PartName="/word/footnotes.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footnotes+xml"/><Override PartName="/word/endnotes.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.endnotes+xml"/><Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/><Override PartName="/customXml/itemProps1.xml" ContentType="application/vnd.openxmlformats-officedocument.customXmlProperties+xml"/></Types>""";
    private const string RootRels="""<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>""";
    private const string DocumentRels="""<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rStyles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="rNumbering" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/><Relationship Id="rComments" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="comments.xml"/><Relationship Id="rCommentsEx" Type="http://schemas.microsoft.com/office/2011/relationships/commentsExtended" Target="commentsExtended.xml"/><Relationship Id="rHeader" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/><Relationship Id="rFooter" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/><Relationship Id="rFootnotes" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footnotes" Target="footnotes.xml"/><Relationship Id="rEndnotes" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/endnotes" Target="endnotes.xml"/><Relationship Id="rImage" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/image1.png"/><Relationship Id="rCustomXml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/customXml" Target="../customXml/item1.xml"/><Relationship Id="rOpaque" Type="urn:stealtheye:relationships:opaque" Target="custom/opaque.xml"/><Relationship Id="rOpaqueBin" Type="urn:stealtheye:relationships:opaque-binary" Target="embeddings/opaque.bin"/></Relationships>""";
    private const string Styles="""<?xml version="1.0" encoding="UTF-8"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:pPr><w:outlineLvl w:val="0"/></w:pPr><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="AdversarialAccent"><w:name w:val="Adversarial Accent"/><w:basedOn w:val="Normal"/><w:rPr><w:i/><w:color w:val="334455"/></w:rPr></w:style></w:styles>""";
    private const string Numbering="""<?xml version="1.0" encoding="UTF-8"?><w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:abstractNum w:abstractNumId="1"><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl><w:lvl w:ilvl="1"><w:start w:val="1"/><w:numFmt w:val="lowerLetter"/><w:lvlText w:val="%2)"/></w:lvl></w:abstractNum><w:num w:numId="1"><w:abstractNumId w:val="1"/></w:num><w:num w:numId="2"><w:abstractNumId w:val="1"/><w:lvlOverride w:ilvl="0"><w:startOverride w:val="3"/></w:lvlOverride></w:num></w:numbering>""";
    private const string Comments="""<?xml version="1.0" encoding="UTF-8"?><w:comments xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml"><w:comment w:id="0" w:author="Root" w:date="2026-08-09T00:00:00Z"><w:p w14:paraId="11111111"><w:r><w:t>Root adversarial comment</w:t></w:r></w:p></w:comment><w:comment w:id="1" w:author="Reply" w:date="2026-08-09T00:01:00Z"><w:p w14:paraId="22222222"><w:r><w:t>Reply adversarial comment</w:t></w:r></w:p></w:comment></w:comments>""";
    private const string CommentsExtended="""<?xml version="1.0" encoding="UTF-8"?><w15:commentsEx xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml"><w15:commentEx w15:paraId="11111111" w15:done="0"/><w15:commentEx w15:paraId="22222222" w15:paraIdParent="11111111" w15:done="0"/></w15:commentsEx>""";
    private const string Header="""<?xml version="1.0" encoding="UTF-8"?><w:hdr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:p><w:r><w:t>F-001 Header</w:t></w:r></w:p></w:hdr>""";
    private const string Footer="""<?xml version="1.0" encoding="UTF-8"?><w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:p><w:fldSimple w:instr=" PAGE "><w:r><w:t>1</w:t></w:r></w:fldSimple></w:p></w:ftr>""";
    private const string Footnotes="""<?xml version="1.0" encoding="UTF-8"?><w:footnotes xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:footnote w:id="-1" w:type="separator"><w:p><w:r><w:separator/></w:r></w:p></w:footnote><w:footnote w:id="0" w:type="continuationSeparator"><w:p><w:r><w:continuationSeparator/></w:r></w:p></w:footnote><w:footnote w:id="1"><w:p><w:r><w:footnoteRef/><w:t> F-001 footnote</w:t></w:r></w:p></w:footnote></w:footnotes>""";
    private const string Endnotes="""<?xml version="1.0" encoding="UTF-8"?><w:endnotes xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:endnote w:id="-1" w:type="separator"><w:p><w:r><w:separator/></w:r></w:p></w:endnote><w:endnote w:id="0" w:type="continuationSeparator"><w:p><w:r><w:continuationSeparator/></w:r></w:p></w:endnote><w:endnote w:id="1"><w:p><w:r><w:endnoteRef/><w:t> F-001 endnote</w:t></w:r></w:p></w:endnote></w:endnotes>""";
    private const string Settings="""<?xml version="1.0" encoding="UTF-8"?><w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:trackRevisions/><w:updateFields w:val="false"/></w:settings>""";
    private const string CustomXml="""<?xml version="1.0" encoding="UTF-8"?><se:payload xmlns:se="urn:stealtheye:f001"><se:value>opaque custom XML payload</se:value></se:payload>""";
    private const string CustomXmlProps="""<?xml version="1.0" encoding="UTF-8"?><ds:datastoreItem ds:itemID="{11111111-2222-4333-8444-555555555555}" xmlns:ds="http://schemas.openxmlformats.org/officeDocument/2006/customXml"><ds:schemaRefs><ds:schemaRef ds:uri="urn:stealtheye:f001"/></ds:schemaRefs></ds:datastoreItem>""";
    private const string CustomXmlRels="""<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/customXmlProps" Target="itemProps1.xml"/></Relationships>""";
    private const string OpaqueCustom="""<?xml version="1.0" encoding="UTF-8"?><opaque xmlns="urn:stealtheye:f001:opaque" required="true">exact opaque provider payload</opaque>""";
    private const string Core="""<?xml version="1.0" encoding="UTF-8"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>F-001 Adversarial Foreign DOCX</dc:title><dc:creator>StealthEyeLLC fixture</dc:creator><dcterms:created xsi:type="dcterms:W3CDTF">2026-08-09T00:00:00Z</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">2026-08-09T00:00:00Z</dcterms:modified></cp:coreProperties>""";
    private const string App="""<?xml version="1.0" encoding="UTF-8"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Application>DOCSeye deterministic fixture generator</Application></Properties>""";
    private const string Document="""
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:ux="urn:stealtheye:f001:unknown" mc:Ignorable="w14 w15 ux"><w:body>
<w:p w14:paraId="10000001"><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>F-001 Adversarial Heading</w:t></w:r></w:p>
<w:p w14:paraId="10000002"><w:pPr><w:pStyle w:val="AdversarialAccent"/></w:pPr><w:bookmarkStart w:id="1" w:name="DOCSEYE_SUPPORTED_EDIT_TARGET"/><w:r><w:t>F001_SUPPORTED_EDIT_TARGET</w:t></w:r><w:bookmarkEnd w:id="1"/></w:p>
<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>Numbered level one</w:t></w:r></w:p><w:p><w:pPr><w:numPr><w:ilvl w:val="1"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>Nested numbered level</w:t></w:r></w:p><w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="2"/></w:numPr></w:pPr><w:r><w:t>Restarted numbering at three</w:t></w:r></w:p>
<w:p><w:commentRangeStart w:id="0"/><w:r><w:t>Commented text</w:t></w:r><w:commentRangeEnd w:id="0"/><w:r><w:commentReference w:id="0"/></w:r></w:p>
<w:p><w:ins w:id="1" w:author="Adversary" w:date="2026-08-09T00:00:00Z"><w:r><w:t>tracked insert</w:t></w:r></w:ins><w:del w:id="2" w:author="Adversary" w:date="2026-08-09T00:00:01Z"><w:r><w:delText>tracked delete</w:delText></w:r></w:del><w:moveFrom w:id="3" w:author="Adversary" w:date="2026-08-09T00:00:02Z"><w:r><w:t>moved from</w:t></w:r></w:moveFrom><w:moveTo w:id="4" w:author="Adversary" w:date="2026-08-09T00:00:03Z"><w:r><w:t>moved to</w:t></w:r></w:moveTo></w:p>
<w:p><w:pPr><w:pPrChange w:id="5" w:author="Adversary" w:date="2026-08-09T00:00:04Z"><w:pPr><w:pStyle w:val="Normal"/></w:pPr></w:pPrChange></w:pPr><w:r><w:t>tracked style change</w:t></w:r></w:p>
<w:p><w:fldSimple w:instr=" DOCPROPERTY Title "><w:r><w:t>F-001</w:t></w:r></w:fldSimple><w:r><w:tab/></w:r><w:fldSimple w:instr=" PAGE "><w:r><w:t>1</w:t></w:r></w:fldSimple></w:p><w:p><w:r><w:fldChar w:fldCharType="begin"/></w:r><w:r><w:instrText> REF targetBookmark </w:instrText></w:r><w:r><w:fldChar w:fldCharType="separate"/></w:r><w:r><w:t>target text</w:t></w:r><w:r><w:fldChar w:fldCharType="end"/></w:r></w:p>
<w:sdt><w:sdtPr><w:alias w:val="Text Control"/><w:tag w:val="text-control"/><w:text/></w:sdtPr><w:sdtContent><w:p><w:r><w:t>controlled text</w:t></w:r></w:p></w:sdtContent></w:sdt><w:sdt><w:sdtPr><w:alias w:val="Enum Control"/><w:tag w:val="enum-control"/><w:dropDownList><w:listItem w:displayText="One" w:value="one"/><w:listItem w:displayText="Two" w:value="two"/></w:dropDownList></w:sdtPr><w:sdtContent><w:p><w:r><w:t>One</w:t></w:r></w:p></w:sdtContent></w:sdt>
<w:p><w:bookmarkStart w:id="2" w:name="targetBookmark"/><w:r><w:t>Bookmark target</w:t></w:r><w:bookmarkEnd w:id="2"/><w:hyperlink w:anchor="targetBookmark"><w:r><w:t> internal reference</w:t></w:r></w:hyperlink></w:p>
<w:tbl><w:tblPr/><w:tblGrid><w:gridCol w:w="2000"/><w:gridCol w:w="2000"/><w:gridCol w:w="2000"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:gridSpan w:val="2"/><w:vMerge w:val="restart"/></w:tcPr><w:p><w:r><w:t>Merged top</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>R0C2</w:t></w:r></w:p></w:tc></w:tr><w:tr><w:tc><w:tcPr><w:gridSpan w:val="2"/><w:vMerge/></w:tcPr><w:p><w:r><w:t>Merged continuation</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Nested table follows</w:t></w:r></w:p><w:tbl><w:tblPr/><w:tblGrid><w:gridCol w:w="900"/><w:gridCol w:w="900"/></w:tblGrid><w:tr><w:tc><w:p><w:r><w:t>N00</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>N01</w:t></w:r></w:p></w:tc></w:tr></w:tbl></w:tc></w:tr></w:tbl>
<w:p><w:r><w:footnoteReference w:id="1"/><w:t> Footnote ref </w:t><w:endnoteReference w:id="1"/><w:t> Endnote ref</w:t></w:r></w:p>
<w:p><w:r><w:t>Figure media relationship rImage targets word/media/image1.png.</w:t></w:r></w:p>
<w:p><m:oMath><m:r><m:t>x+y=z</m:t></m:r></m:oMath></w:p>
<mc:AlternateContent><mc:Choice Requires="ux"><w:p><w:r><w:t>Unknown choice </w:t></w:r><ux:opaque ux:required="true">unknown required provider meaning</ux:opaque></w:p></mc:Choice><mc:Fallback><w:p><w:r><w:t>Static compatible fallback</w:t></w:r></w:p></mc:Fallback></mc:AlternateContent>
<w:p><w:r><w:t>Opaque relationships: rOpaque and rOpaqueBin are preserved inertly.</w:t></w:r></w:p>
<w:sectPr><w:headerReference w:type="default" r:id="rHeader"/><w:footerReference w:type="default" r:id="rFooter"/><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720"/></w:sectPr>
</w:body></w:document>
""";
}