using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using DOCSeye.Core;
using DOCSeye.Fixtures;
using DOCSeye.Providers;
using DOCSeye.Storage.Sqlite;

string repo=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"..","..","..","..",".."));string work=Path.Combine(repo,"artifacts","milestone-b");if(Directory.Exists(work))Directory.Delete(work,true);Directory.CreateDirectory(work);Directory.CreateDirectory(Path.Combine(repo,"evidence"));
string dnd=Path.Combine(work,"B.dnd"),manifestPath=Path.Combine(work,"N-001-B.manifest.json");N001Generator.Write(dnd,manifestPath);string node=@"C:\AgentBrowser\tools\node-v24.18.1-win-x64\node.exe",writer=Path.Combine(repo,"tools","independent-writer","independent-writer.mjs");
var checks=new List<object>();var transactionEvidence=new List<object>();
void Expect(bool ok,string msg){if(!ok)throw new InvalidOperationException(msg);}void Pass(string id,object data){checks.Add(new{id,result="PASS",data});Console.WriteLine(id+" PASS");}
string Sha(string path){using var fs=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete);return Convert.ToHexString(SHA256.HashData(fs)).ToLowerInvariant();}
string Run(string exe,params string[] args){var psi=new ProcessStartInfo(exe){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true};foreach(string a in args)psi.ArgumentList.Add(a);using var p=Process.Start(psi)??throw new InvalidOperationException("start failed");var ot=p.StandardOutput.ReadToEndAsync();var et=p.StandardError.ReadToEndAsync();if(!p.WaitForExit(30000)){try{p.Kill(true);}catch{}throw new TimeoutException("process timeout: "+exe);}Task.WaitAll(ot,et);string o=ot.Result,e=et.Result;if(p.ExitCode!=0)throw new InvalidOperationException($"{exe} exit {p.ExitCode}: {e}");return o.Trim();}
SemanticObject Obj(SemanticState s,Func<SemanticObject,bool> p)=>s.Objects.Values.First(o=>!o.Retired&&p(o));
string Text(SemanticObject o)=>(string)o.Data["text"]!;int ScalarIndex(string text,string substring){int utf=text.IndexOf(substring,StringComparison.Ordinal);if(utf<0)throw new InvalidOperationException("substring missing: "+substring);return UnicodeText.ScalarCount(text[..utf]);}

using var session=NativeDocumentSession.Open(dnd,true);Expect(session.WriteAuthority,"B fixture not writable");var initial=session.LoadState();var initialHead=session.ReadHead();var originalExtensions=initial.Extensions.ToDictionary(k=>k.Key,v=>v.Value.ExactPayload.ToArray());
var fixtureRanges=initial.Ranges.ToDictionary(k=>k.Key,v=>v.Value);var fixtureBoundaries=initial.Boundaries.ToDictionary(k=>k.Key,v=>v.Value);Expect(fixtureRanges.Count==6,"N-001 retained range cardinality drift");Guid fixtureCommentRange=fixtureRanges.Values.Single(r=>r.Kind=="comment").Id,fixtureStyleRange=fixtureRanges.Values.Single(r=>r.Kind=="style").Id,fixtureNamedRange=fixtureRanges.Values.Single(r=>r.Kind=="named_range").Id,fixtureSuggestionRange=fixtureRanges.Values.Single(r=>r.Kind=="suggestion").Id,fixturePointRange=fixtureRanges.Values.Single(r=>r.Kind=="named_point_anchor").Id,fixtureMultiRange=fixtureRanges.Values.Single(r=>r.Kind=="cross_block_multi_interval").Id;
Guid root=Obj(initial,o=>o.Type=="document").Id;Guid mainFlow=Obj(initial,o=>o.Type=="flow"&&o.Role=="main").Id;var sections=initial.Objects.Values.Where(o=>!o.Retired&&o.Type=="section"&&o.ParentId==mainFlow).OrderBy(o=>o.Order).ToArray();
Guid section1=sections[0].Id,section2=sections[1].Id;Guid safeReflowBody=Obj(initial,o=>o.Type=="text_block"&&o.Role=="body"&&Text(o).StartsWith("An early edit here",StringComparison.Ordinal)).Id;Guid arabicBody=Obj(initial,o=>o.Type=="text_block"&&o.Role=="body"&&Text(o).StartsWith("Arabic logical text",StringComparison.Ordinal)).Id;Guid mixedBidiBody=Obj(initial,o=>o.Type=="text_block"&&o.Role=="body"&&Text(o).StartsWith("Mixed bidi",StringComparison.Ordinal)).Id;Guid emojiBody=Obj(initial,o=>o.Type=="text_block"&&o.Role=="body"&&Text(o).StartsWith("Emoji ZWJ",StringComparison.Ordinal)).Id;Guid decomposedBody=Obj(initial,o=>o.Type=="text_block"&&o.Role=="body"&&Text(o).StartsWith("Decomposed sequence",StringComparison.Ordinal)).Id;
var requiredExt=initial.Extensions.Values.Single(e=>e.Required&&e.CoverageKind==ExtensionCoverageKind.TextInterval);Guid requiredTarget=requiredExt.TargetId!.Value;int requiredStart=initial.Boundaries[requiredExt.StartBoundaryId!.Value].ScalarOffset;int requiredEnd=initial.Boundaries[requiredExt.EndBoundaryId!.Value].ScalarOffset;
Guid topList=Obj(initial,o=>o.Type=="list"&&o.ParentId==section2).Id;Guid mainTable=Obj(initial,o=>o.Type=="table"&&o.ParentId==section2&&Convert.ToInt32(o.Data["rows"])==4).Id;Guid mergedRegion=Obj(initial,o=>o.Type=="table_cell"&&o.ParentId==mainTable&&Convert.ToInt32(o.Data["row_span"])==2&&Convert.ToInt32(o.Data["column_span"])==2).Id;Guid nestedTable=Obj(initial,o=>o.Type=="table"&&o.ParentId is Guid p&&initial.Objects.TryGetValue(p,out var po)&&po.Type=="table_cell").Id;
Guid accentToken=Obj(initial,o=>o.Type=="theme_token"&&(o.Data["name"] as string)=="color.accent").Id;Guid enumControl=Obj(initial,o=>o.Type=="control"&&(o.Data["control_type"] as string)=="enum").Id;Guid displayMath=Obj(initial,o=>o.Type=="math"&&Convert.ToBoolean(o.Data["display"])).Id;Guid texFacet=initial.ProviderFacets.Values.Single(f=>f.TargetId==displayMath&&f.Provider=="tex").Id;Guid bibRecord=Obj(initial,o=>o.Type=="bibliographic_record").Id;Guid fixtureInsertSuggestion=Obj(initial,o=>o.Type=="suggestion"&&(o.Data["kind"] as string)=="insert").Id;Guid genericTopologyExt=initial.Extensions.Values.Single(e=>e.CoverageKind==ExtensionCoverageKind.TopologyRegion&&e.EditPolicy==ExtensionEditPolicy.GenericTransform).ExtensionId;Guid pageCountField=Obj(initial,o=>o.Type=="field"&&(o.Data["class"] as string)=="page_count").Id;Guid fixtureFootnote=Obj(initial,o=>o.Type=="note"&&o.Role=="footnote").Id;Guid headerFlow=Obj(initial,o=>o.Type=="flow"&&o.Role=="header").Id;Guid footerFlow=Obj(initial,o=>o.Type=="flow"&&o.Role=="footer").Id;Guid headerTextId=Obj(initial,o=>o.Type=="text_block"&&o.ParentId==headerFlow).Id;Guid footerTextId=Obj(initial,o=>o.Type=="text_block"&&o.ParentId==footerFlow).Id;

// B-T1: one coherent transaction with structure, text, list, table, style, comment, field, layout and two overlapping retained ranges.
var t1=session.BeginTransaction();Guid appendix=t1.CreateObject("section",mainFlow,"section",new(StringComparer.Ordinal){{"name","Appendix"},{"columns",1},{"page_numbering","continue"}});int arabicEnd=UnicodeText.ScalarCount(Text(t1.State.Objects[arabicBody]));string reflowClause=string.Concat(Enumerable.Repeat(" \u0641\u0642\u0631\u0629 \u0625\u0636\u0627\u0641\u064a\u0629 \u0644\u0636\u063a\u0637 \u0625\u0639\u0627\u062f\u0629 \u0627\u0644\u062a\u062f\u0641\u0642.",220));t1.InsertText(arabicBody,arabicEnd,reflowClause,true);Guid listItem=t1.InsertListItem(topList,2,["Inserted multi-block list item -- first block.","Inserted multi-block list item -- second block."],0,5);byte[] t1TopologyPayload=Encoding.UTF8.GetBytes("B-T1 transformed topology extension for main-table row insertion");t1.TransformExtension(genericTopologyExt,t1TopologyPayload);var row=t1.InsertTableRow(mainTable,4,["B1-0","B1-1","B1-2","B1-3"]);t1.SetObjectProperty(mainTable,"rows",5,true,"table_row_count");t1.SetObjectProperty(accentToken,"value","#334455",true,"theme_token_update");Guid overlap1=t1.RetainRange(safeReflowBody,5,25,"comment",EdgeAffinity.ExcludeAtEdge,EdgeAffinity.ExcludeAtEdge,true);Guid overlap2=t1.RetainRange(safeReflowBody,15,35,"style",EdgeAffinity.IncludeAtEdge,EdgeAffinity.IncludeAtEdge,true);Guid thread=t1.CreateObject("comment_thread",root,"comment_thread",new(StringComparer.Ordinal){{"state","open"},{"target_range_id",overlap1}},null,false);Guid comment=t1.CreateObject("comment",thread,"comment",new(StringComparer.Ordinal){{"author","B-author"},{"timestamp","2026-08-09T00:00:00Z"},{"body","B transaction thread"},{"target_range_id",overlap1},{"quoted_display","An early edit"}},null,false);Guid countField=t1.CreateObject("field",root,"field",new(StringComparer.Ordinal){{"class","simple_count"},{"source","count(text_block)"},{"dependencies",new object?[]{mainFlow}},{"cached_result",null},{"result_semantic_revision",null},{"staleness","stale"},{"evaluation_policy","on_semantic_commit"}},null,false);t1.SetObjectProperty(section2,"margin","0.65in",true,"layout_margin");t1.AddLayoutInvalidation("page-count-field");
string beforeT1Sha=Sha(dnd);var r1=session.CommitTransaction(t1,initialHead.RevisionId,"B-T1");Expect(r1.Success&&r1.Head is not null&&r1.Delta is not null,"B-T1 failed: "+r1.Classification+" "+string.Join(";",r1.Diagnostics));var t1Head=r1.Head!;var t1Delta=r1.Delta!;Expect(t1Head.Sequence==initialHead.Sequence+1&&t1Head.Parents.SequenceEqual([initialHead.RevisionId]),"B-T1 revision arithmetic/parent failed");Expect(t1Delta.FromRevisionId==initialHead.RevisionId&&t1Delta.ToRevisionId==t1Head.RevisionId,"B-T1 delta revisions wrong");Expect(t1Delta.LayoutInvalidations.Count>0,"B-T1 layout invalidation missing");Expect(Sha(dnd)!=beforeT1Sha,"B-T1 did not publish artifact bytes");transactionEvidence.Add(new{name="B-T1",revision=Ids.Lower(t1Head.RevisionId),root=Convert.ToHexString(t1Head.SemanticRoot).ToLowerInvariant(),operations=t1.Operations.Count,delta_bytes=t1Delta.ExactBytes.Length,layout_invalidations=t1Delta.LayoutInvalidations});Pass("B-T1",new{operations=t1.Operations.Count,revision=Ids.Lower(t1Head.RevisionId),overlap_ranges=new[]{Ids.Lower(overlap1),Ids.Lower(overlap2)},appendix=Ids.Lower(appendix),list_item=Ids.Lower(listItem),row=Ids.Lower(row.Row)});

// Exact independent external descendant and reconciliation before T2.
var afterT1=session.LoadState();Guid externalMove=mixedBidiBody;string extJson=Run(node,writer,"move-object",dnd,Ids.Lower(externalMove),"0");using(var edoc=JsonDocument.Parse(extJson)){Expect(edoc.RootElement.GetProperty("classification").GetString()=="committed","external commit failed");}var reconcile=session.ReconcileExternal(true);Expect(reconcile.Writable,"external commit reconciliation invalid: "+reconcile.Classification);var externalHead=session.ReadHead();Expect(externalHead.Parents.Count==1&&externalHead.Parents[0]==t1Head.RevisionId,"external head is not exact T1 descendant");Expect(session.LoadState().Objects.ContainsKey(externalMove),"external reconciliation lost moved identity");Pass("B-EXTERNAL-RECONCILE",new{object_id=Ids.Lower(externalMove),from=Ids.Lower(t1Head.RevisionId),to=Ids.Lower(externalHead.RevisionId),classification="exact_descendant"});

// B-T2: review/control/note/citation/figure/math/extensions, plus exact second duplicate-sentence edit.
var t2=session.BeginTransaction();Guid replaceSuggestion=t2.CreateObject("suggestion",root,"suggestion",new(StringComparer.Ordinal){{"kind","replace"},{"state","active"},{"target_id",safeReflowBody},{"range_id",overlap2}},null,false);t2.SetObjectProperty(enumControl,"value","reviewed",false,"control_set_enum");Guid note=t2.CreateObject("note",root,"footnote",new(StringComparer.Ordinal){{"note_kind","footnote"}});Guid noteFlow=t2.CreateObject("flow",note,"note_body",new(StringComparer.Ordinal){{"kind","note_body"}});t2.CreateObject("text_block",noteFlow,"note_body",new(StringComparer.Ordinal){{"text","B transaction footnote body."}});t2.CreateObject("note_reference",safeReflowBody,"note_reference",new(StringComparer.Ordinal){{"note_id",note},{"occurrence_kind","footnote"}});Guid citation=t2.CreateObject("citation",safeReflowBody,"citation",new(StringComparer.Ordinal){{"record_id",bibRecord},{"locator","B-T2"}},null,false);byte[] rasterDigest=initial.Assets.Values.First(a=>a.State=="embedded"&&a.Length<1024).Digest;Guid figure=t2.CreateObject("figure",section2,"figure",new(StringComparer.Ordinal){{"asset_digest",rasterDigest},{"caption","B shared raster figure"},{"alt_text","B occurrence sharing an existing embedded asset"},{"placement","anchored"},{"wrap","square"},{"crop","none"},{"sizing","1.75in"}});t2.SetObjectProperty(displayMath,"presentation_mathml","<math xmlns=\"http://www.w3.org/1998/Math/MathML\" display=\"block\"><mrow><mi>a</mi><mo>+</mo><mi>b</mi><mo>=</mo><mi>c</mi></mrow></math>",true,"math_update");t2.SetProviderFacetAlignment(texFacet,"partially_stale");byte[] extPayload=Encoding.UTF8.GetBytes("B move-with-target extension exact payload");Guid movingExt=Ids.NewV4();t2.AddExtension(new(movingExt,"urn:docseye:B:move","move-facet",1,0,"bytes",extPayload,SHA256.HashData(extPayload),ExtensionCoverageKind.Object,safeReflowBody,null,null,null,ExtensionEditPolicy.MoveWithTarget,false,null));t2.MoveExtensionWithOwner(movingExt,figure);
var duplicateBodies=t2.State.Objects.Values.Where(o=>!o.Retired&&o.Type=="text_block"&&o.Role=="body"&&Text(o)=="Identity must never follow duplicate text.").ToArray();Guid secondDuplicate=duplicateBodies.Single(o=>o.ParentId==section2).Id;t2.ReplaceText(secondDuplicate,0,UnicodeText.ScalarCount(Text(t2.State.Objects[secondDuplicate])),"Identity must never follow duplicate text -- second occurrence updated.",true);
var r2=session.CommitTransaction(t2,externalHead.RevisionId,"B-T2");Expect(r2.Success&&r2.Head is not null&&r2.Delta is not null,"B-T2 failed: "+r2.Classification+" "+string.Join(";",r2.Diagnostics));var t2Head=r2.Head!;Expect(t2Head.Parents.SequenceEqual([externalHead.RevisionId]),"B-T2 parent not external head");transactionEvidence.Add(new{name="B-T2",revision=Ids.Lower(t2Head.RevisionId),root=Convert.ToHexString(t2Head.SemanticRoot).ToLowerInvariant(),operations=t2.Operations.Count,delta_bytes=r2.Delta!.ExactBytes.Length,layout_invalidations=r2.Delta!.LayoutInvalidations});Pass("B-T2",new{operations=t2.Operations.Count,revision=Ids.Lower(t2Head.RevisionId),suggestion=Ids.Lower(replaceSuggestion),note=Ids.Lower(note),citation=Ids.Lower(citation),figure=Ids.Lower(figure),extension=Ids.Lower(movingExt),second_duplicate=Ids.Lower(secondDuplicate)});

// Required refusal branches must happen before write.
string staleBefore=Sha(dnd);var staleBuilder=session.BeginTransaction();staleBuilder.SetObjectProperty(enumControl,"value","must-not-write",false,"stale_probe");var stale=session.CommitTransaction(staleBuilder,t1Head.RevisionId,"B-stale-probe");Expect(!stale.Success&&stale.Classification=="stale_revision"&&Sha(dnd)==staleBefore,"stale T1 revision wrote or misclassified");
string requiredBefore=Sha(dnd);var requiredBuilder=session.BeginTransaction();string requiredClass="";try{requiredBuilder.InsertText(requiredTarget,requiredStart+1,"X",true);throw new InvalidOperationException("required extension edit unexpectedly staged");}catch(SemanticRefusalException ex){requiredClass=ex.Code;}Expect(requiredClass=="blocked_required_extension"&&Sha(dnd)==requiredBefore&&session.ReadHead().RevisionId==t2Head.RevisionId,"required extension intersection wrote or misclassified");Pass("B-REFUSALS",new{stale="stale_revision",required_extension=requiredClass,writes=0});

// B-T3: boundary killer, text/table split+merge, review resolution, layout pressure and extension transform.
var beforeT3=session.LoadState();var coRanges=beforeT3.Ranges.Values.Where(r=>r.Kind is "named_range" or "suggestion").Where(r=>r.EffectiveIntervals.Count==1).Select(r=>(r,interval:r.EffectiveIntervals[0],s:beforeT3.Boundaries[r.EffectiveIntervals[0].StartBoundaryId],e:beforeT3.Boundaries[r.EffectiveIntervals[0].EndBoundaryId])).Where(x=>x.s.OwnerId==decomposedBody&&x.s.ScalarOffset==4).ToArray();Expect(coRanges.Length==2&&coRanges[0].s.Id!=coRanges[1].s.Id,"fixture co-located independent boundaries missing");var coBefore=coRanges.ToDictionary(x=>x.s.Id,x=>x.s.ScalarOffset);
var t3=session.BeginTransaction();t3.InsertText(decomposedBody,4,"Q",true);var coAfterInsert=coRanges.ToDictionary(x=>x.s.Id,x=>t3.State.Boundaries[x.s.Id].ScalarOffset);Expect(coAfterInsert.Values.Distinct().Count()>1,"co-located independent affinities aliased on edge insertion");t3.DeleteText(decomposedBody,6,2,true);
// Complete deletion of T1 comment range should orphan comment target while overlapping style range only shrinks.
var commentRange=t3.State.Ranges[overlap1];var ci=commentRange.EffectiveIntervals[0];var cs=t3.State.Boundaries[ci.StartBoundaryId];var ce=t3.State.Boundaries[ci.EndBoundaryId];Expect(cs.OwnerId==ce.OwnerId,"B comment target not single-block before deletion");int completeStart=Math.Min(cs.ScalarOffset,ce.ScalarOffset),completeCount=Math.Abs(ce.ScalarOffset-cs.ScalarOffset);t3.DeleteText(cs.OwnerId,completeStart,completeCount,true);Expect(t3.State.Ranges[overlap1].State=="orphaned","complete comment target did not orphan");Expect(t3.State.Ranges[overlap2].State!="destroyed","overlapping style range was incorrectly destroyed by partial deletion");
// Emoji ZWJ human-facing replacement and mixed bidi logical edit.
string emojiText=Text(t3.State.Objects[emojiBody]),family="\U0001F469\u200D\U0001F469\u200D\U0001F467\u200D\U0001F467";int emojiAt=ScalarIndex(emojiText,family);t3.ReplaceText(emojiBody,emojiAt,UnicodeText.ScalarCount(family),"\U0001F468\u200D\U0001F469\u200D\U0001F467\u200D\U0001F466",true);string bidiText=Text(t3.State.Objects[mixedBidiBody]);int bidiAt=ScalarIndex(bidiText,"English");t3.ReplaceText(mixedBidiBody,bidiAt,UnicodeText.ScalarCount("English"),"Latin",true);
// Split then merge the reflow-pressure block carrying surviving range boundaries.
var splitSource=t3.State.Objects[decomposedBody];int splitAt=Math.Max(2,UnicodeText.ScalarCount(Text(splitSource))/2);var split=t3.SplitText(decomposedBody,splitAt);Guid mergeResult=t3.MergeText(split.Left,split.Right);Expect(t3.State.Objects[decomposedBody].Retired&&t3.State.Objects[split.Left].Retired&&t3.State.Objects[split.Right].Retired&&!t3.State.Objects[mergeResult].Retired,"text split/merge retirement contract failed");
// Split original 2x2 merged cell and merge two successors.
byte[] topologyPayload=Encoding.UTF8.GetBytes("B-T3 transformed topology extension for main-table merge/split");t3.TransformExtension(genericTopologyExt,topologyPayload);Guid mergedAgain=t3.MergeTableCells(mainTable,row.Cells.Take(2).ToArray(),4,0,1,2,"B-T3 temporary merged result");var splitCells=t3.SplitTableCell(mainTable,mergedAgain,1,2);t3.ResolveSuggestion(fixtureInsertSuggestion,"accept");t3.SetObjectProperty(section1,"layout_pressure","B-T3-reflow",true,"layout_pressure_update");Guid policyBoundary=t3.State.Ranges.Values.Single(r=>r.Kind=="named_point_anchor").EffectiveIntervals[0].StartBoundaryId;t3.SetBoundaryAffinity(policyBoundary,EdgeAffinity.AfterInsertion);Guid copiedExt=t3.CopyTransformableExtension(genericTopologyExt,new Dictionary<Guid,Guid>{{mainTable,nestedTable}});t3.AddLayoutInvalidation("header-footer-page-field");
var r3=session.CommitTransaction(t3,t2Head.RevisionId,"B-T3");Expect(r3.Success&&r3.Head is not null&&r3.Delta is not null,"B-T3 failed: "+r3.Classification+" "+string.Join(";",r3.Diagnostics));var t3Head=r3.Head!;transactionEvidence.Add(new{name="B-T3",revision=Ids.Lower(t3Head.RevisionId),root=Convert.ToHexString(t3Head.SemanticRoot).ToLowerInvariant(),operations=t3.Operations.Count,delta_bytes=r3.Delta!.ExactBytes.Length,layout_invalidations=r3.Delta!.LayoutInvalidations});Pass("B-T3",new{operations=t3.Operations.Count,revision=Ids.Lower(t3Head.RevisionId),merge_result=Ids.Lower(mergeResult),table_merge=Ids.Lower(mergedAgain),table_split_successors=splitCells.Select(Ids.Lower).ToArray(),copied_extension=Ids.Lower(copiedExt),comment_target_state=t3.State.Ranges[overlap1].State,style_target_state=t3.State.Ranges[overlap2].State});

// Exact postconditions, extension preservation, delta coverage and expired cursor behavior.
var final=session.LoadState();var finalHead=session.ReadHead();Expect(finalHead.RevisionId==t3Head.RevisionId&&finalHead.SemanticRoot.SequenceEqual(final.ComputeRoot()),"final head/root mismatch");Expect(final.Objects[secondDuplicate].Data["text"] is string second&&second.Contains("second occurrence updated",StringComparison.Ordinal),"duplicate quotation edit hit wrong occurrence");Expect(final.Objects.Values.Count(o=>!o.Retired&&o.Type=="text_block"&&o.Role=="body"&&Text(o)=="Identity must never follow duplicate text.")==2,"unrequested duplicate sentence mutation");Expect(originalExtensions.Where(kv=>kv.Key!=genericTopologyExt).All(kv=>final.Extensions.TryGetValue(kv.Key,out var e)&&e.ExactPayload.SequenceEqual(kv.Value)&&e.DigestValid),"untouched original extension payload loss");Expect(final.Extensions[genericTopologyExt].ExactPayload.SequenceEqual(topologyPayload)&&final.Extensions[genericTopologyExt].DigestValid,"declared topology extension transform not persisted exactly");Expect(final.Extensions[copiedExt].TargetId==nestedTable&&final.Extensions[copiedExt].DigestValid,"generic extension remap incorrect");Expect(final.ProviderFacets[texFacet].Alignment=="partially_stale","native math edit did not stale TeX facet");Expect(final.Ranges[overlap1].State=="orphaned"&&final.Ranges[overlap2].State!="destroyed","range lifecycle postcondition wrong");
var fixtureRangeIds=fixtureRanges.Keys.OrderBy(Ids.Lower,StringComparer.Ordinal).ToArray();foreach(Guid rangeId in fixtureRangeIds){Expect(final.Ranges.TryGetValue(rangeId,out var current),"fixture retained range identity missing: "+Ids.Lower(rangeId));var before=fixtureRanges[rangeId];var expectedBoundaryIds=before.EffectiveIntervals.SelectMany(x=>new[]{x.StartBoundaryId,x.EndBoundaryId}).ToArray();var actualBoundaryIds=current!.EffectiveIntervals.SelectMany(x=>new[]{x.StartBoundaryId,x.EndBoundaryId}).ToArray();Expect(expectedBoundaryIds.SequenceEqual(actualBoundaryIds),"fixture range boundary identity/topology changed: "+Ids.Lower(rangeId));Expect(actualBoundaryIds.All(id=>final.Boundaries.TryGetValue(id,out var b)&&b.State!=AnchorState.Ambiguous),"fixture boundary became ambiguous: "+Ids.Lower(rangeId));}
foreach(Guid rangeId in new[]{fixtureCommentRange,fixtureStyleRange})foreach(Guid boundaryId in fixtureRanges[rangeId].EffectiveIntervals.SelectMany(x=>new[]{x.StartBoundaryId,x.EndBoundaryId}).Distinct()){var before=fixtureBoundaries[boundaryId];var after=final.Boundaries[boundaryId];Expect(after.OwnerId==before.OwnerId&&after.ScalarOffset==before.ScalarOffset&&after.Affinity==before.Affinity&&after.State==before.State,"untouched comment/style fixture boundary mutated");}
var namedBefore=fixtureRanges[fixtureNamedRange];var namedStart=namedBefore.EffectiveIntervals[0].StartBoundaryId;var namedEnd=namedBefore.EffectiveIntervals[0].EndBoundaryId;Expect(final.Ranges[fixtureNamedRange].State=="live"&&final.Boundaries[namedStart].OwnerId==mergeResult&&final.Boundaries[namedEnd].OwnerId==mergeResult,"named range did not preserve boundary identity through split/merge");Expect(final.Boundaries[namedStart].ScalarOffset==fixtureBoundaries[namedStart].ScalarOffset+1&&final.Boundaries[namedEnd].ScalarOffset==fixtureBoundaries[namedEnd].ScalarOffset-1,"named range insertion/deletion mapping wrong");
var suggestionBefore=fixtureRanges[fixtureSuggestionRange];var suggestionBoundaryIds=suggestionBefore.EffectiveIntervals.SelectMany(x=>new[]{x.StartBoundaryId,x.EndBoundaryId}).Distinct().ToArray();Expect(final.Ranges[fixtureSuggestionRange].State=="destroyed"&&suggestionBoundaryIds.All(id=>final.Boundaries[id].State==AnchorState.Destroyed&&final.Boundaries[id].OwnerId==mergeResult),"resolved fixture suggestion range/boundaries not retired exactly");Expect(final.Boundaries[namedStart].ScalarOffset!=final.Boundaries[suggestionBoundaryIds[0]].ScalarOffset,"co-located independent boundary affinities were aliased");
var pointBefore=fixtureRanges[fixturePointRange];Guid pointBoundary=pointBefore.EffectiveIntervals[0].StartBoundaryId;Expect(final.Ranges[fixturePointRange].State=="live"&&pointBefore.EffectiveIntervals[0].StartBoundaryId==pointBefore.EffectiveIntervals[0].EndBoundaryId&&final.Boundaries[pointBoundary].OwnerId==fixtureBoundaries[pointBoundary].OwnerId&&final.Boundaries[pointBoundary].ScalarOffset==fixtureBoundaries[pointBoundary].ScalarOffset&&final.Boundaries[pointBoundary].Affinity==EdgeAffinity.AfterInsertion,"named point anchor move/affinity contract failed");
var multiBefore=fixtureRanges[fixtureMultiRange];Expect(final.Ranges[fixtureMultiRange].State=="live"&&final.Ranges[fixtureMultiRange].EffectiveIntervals.Count==2,"cross-block multi-interval topology lost");foreach(Guid boundaryId in multiBefore.EffectiveIntervals.SelectMany(x=>new[]{x.StartBoundaryId,x.EndBoundaryId}).Distinct()){var before=fixtureBoundaries[boundaryId];var after=final.Boundaries[boundaryId];Expect(after.OwnerId==before.OwnerId&&after.ScalarOffset==before.ScalarOffset&&after.Affinity==before.Affinity&&after.State==before.State,"cross-block multi-interval boundary mutated unexpectedly");}
Pass("B-SIX-RANGES",new{canonical_ranges=6,range_ids_preserved=6,boundary_ids_preserved=true,ambiguous=0,comment_style_untouched=true,named_range_split_merge_exact=true,suggestion_retired_exact=true,point_affinity_exact=true,multi_interval_count=2});
var allDeltas=session.ReadDeltas(0);Expect(!allDeltas.ResyncRequired&&allDeltas.Deltas.Count==4,"expected exactly T1 + external + T2 + T3 deltas");var semanticDeltas=allDeltas.Deltas.Select(d=>(Dictionary<string,object?>)CanonicalCbor.Decode(d)!).Where(m=>Equals(m["kind"],"semantic_transaction")).ToArray();Expect(semanticDeltas.Length==3,"B did not emit exactly three semantic transaction deltas");Expect((Guid)semanticDeltas[0]["from_revision_id"]! == initialHead.RevisionId && (Guid)semanticDeltas[0]["to_revision_id"]! == t1Head.RevisionId && (Guid)semanticDeltas[1]["from_revision_id"]! == externalHead.RevisionId && (Guid)semanticDeltas[1]["to_revision_id"]! == t2Head.RevisionId && (Guid)semanticDeltas[2]["from_revision_id"]! == t2Head.RevisionId && (Guid)semanticDeltas[2]["to_revision_id"]! == t3Head.RevisionId,"semantic delta revision scopes wrong");
session.PruneExpiredWitnesses(finalHead.Sequence);var expired=session.ReadDeltas(0);Expect(expired.ResyncRequired&&expired.Classification=="resync_required","expired cursor did not require resync");Pass("B-SEMANTIC-POSTCONDITIONS",new{requested_postconditions_percent=100,unrequested_semantic_mutations=0,semantic_transaction_deltas=3,external_deltas=1,required_extension_preservation_percent=100,quote_rebounds=0,resync_required=expired.ResyncRequired});

// Native final-state render acceptance: continuous HTML + tagged PDF/UA-1 with exact source qualification and measured reflow.
var renderManifest=N001Generator.Generate().Manifest;var requiredIds=renderManifest.Objects.Where(o=>o.RequiredRenderMapping).Select(o=>Guid.Parse(o.Id)).ToArray();var renderableTypes=new HashSet<string>(["text_block","list_item","table","table_cell","figure","note","link","math"],StringComparer.Ordinal);var renderExemptions=renderManifest.Objects.Where(o=>renderableTypes.Contains(o.Type)&&!o.RequiredRenderMapping).Select(o=>Guid.Parse(o.Id)).ToArray();Expect(renderExemptions.SequenceEqual([decomposedBody]),"fixture render exemption drift");var renderIds=requiredIds.Append(pageCountField).Distinct().ToArray();Expect(requiredIds.All(id=>final.Objects.TryGetValue(id,out var ro)&&!ro.Retired),"required render fixture identity retired before render");
var fontFiles=new Dictionary<string,string>(StringComparer.Ordinal){{"Segoe UI",@"C:\Windows\Fonts\segoeui.ttf"},{"Segoe UI Bold",@"C:\Windows\Fonts\segoeuib.ttf"},{"Nirmala UI",@"C:\Windows\Fonts\Nirmala.ttc"},{"Yu Gothic",@"C:\Windows\Fonts\YuGothR.ttc"},{"Yu Gothic Bold",@"C:\Windows\Fonts\YuGothB.ttc"},{"Segoe UI Emoji",@"C:\Windows\Fonts\seguiemj.ttf"},{"Arial",@"C:\Windows\Fonts\arial.ttf"}};var fontDigests=fontFiles.ToDictionary(k=>k.Key,v=>Sha(v.Value),StringComparer.Ordinal);
string typstExe=Path.Combine(repo,".tools","typst","typst-x86_64-pc-windows-msvc","typst.exe"),veraPdfBat=Path.Combine(repo,".tools","verapdf","verapdf.bat"),javaHome=Path.Combine(repo,".tools","java","jdk-25.0.4+7-jre"),chrome=Path.Combine(repo,".tools","chrome","chrome-win64","chrome.exe"),figureSvg=Path.Combine(repo,"tests","render","semantic-figure.svg");
var pdfEnv=new ProviderEnvironment("Typst","0.15.1 (2d99e029)","en-US","Typst 0.15.1 bundled hyphenation",fontDigests,new Dictionary<string,string>(StringComparer.Ordinal){{"pdf_standard","PDF/UA-1"},{"a11y_extras","enabled"},{"paper","US Letter"},{"font_path",@"C:\Windows\Fonts"}});var htmlEnv=new ProviderEnvironment("DOCSeye HTML","1","en-US","browser CSS line breaking",fontDigests,new Dictionary<string,string>(StringComparer.Ordinal){{"mode","continuous accessible HTML"},{"browser_candidate","Chrome for Testing 151.0.7922.77"},{"browser_path",chrome}});
var pdfProvider=new TypstPdfProvider();var htmlProvider=new HtmlProvider();var basePdf=pdfProvider.Render(initial,initialHead,Path.Combine(work,"render-base"),renderIds,pdfEnv,typstExe,veraPdfBat,javaHome,figureSvg);var finalHtml=htmlProvider.Render(final,finalHead,Path.Combine(work,"render-final","document.html"),renderIds,htmlEnv);var finalPdf=pdfProvider.Render(final,finalHead,Path.Combine(work,"render-final"),renderIds,pdfEnv,typstExe,veraPdfBat,javaHome,figureSvg);
Expect(finalHtml.LayoutRevision.SemanticRevisionId==finalHead.RevisionId&&finalPdf.LayoutRevision.SemanticRevisionId==finalHead.RevisionId&&finalHtml.LayoutRevision.SemanticRoot==Convert.ToHexString(finalHead.SemanticRoot).ToLowerInvariant()&&finalPdf.LayoutRevision.SemanticRoot==Convert.ToHexString(finalHead.SemanticRoot).ToLowerInvariant(),"render source revision/root qualification mismatch");Expect(requiredIds.All(id=>finalHtml.Mapping.ContainsKey(id)&&finalPdf.Mapping.ContainsKey(id)),"required semantic-to-render mapping below 100%");
string htmlText=File.ReadAllText(finalHtml.Path);Expect(htmlText.Contains("docseye-revision",StringComparison.Ordinal)&&htmlText.Contains(Ids.Lower(finalHead.RevisionId),StringComparison.Ordinal)&&htmlText.Contains("<table",StringComparison.OrdinalIgnoreCase)&&htmlText.Contains("aria-label",StringComparison.OrdinalIgnoreCase)&&htmlText.Contains("href=",StringComparison.OrdinalIgnoreCase)&&htmlText.Contains("data-docseye-object-id",StringComparison.Ordinal),"continuous HTML semantic/source validation failed");
var baseTable=basePdf.Mapping[mainTable];var finalTable=finalPdf.Mapping[mainTable];var baseNote=basePdf.Mapping[fixtureFootnote];var finalNote=finalPdf.Mapping[fixtureFootnote];var baseHeader=basePdf.Mapping[headerTextId];var finalHeader=finalPdf.Mapping[headerTextId];var baseFooter=basePdf.Mapping[footerTextId];var finalFooter=finalPdf.Mapping[footerTextId];var basePageField=basePdf.Mapping[pageCountField];var finalPageField=finalPdf.Mapping[pageCountField];bool tableReflow=baseTable.Page!=finalTable.Page||baseTable.X!=finalTable.X||baseTable.Y!=finalTable.Y;bool noteReflow=baseNote.Page!=finalNote.Page||baseNote.X!=finalNote.X||baseNote.Y!=finalNote.Y;bool pageCountChanged=baseHeader.Occurrences!=finalHeader.Occurrences;Expect(tableReflow,"early semantic edit did not reflow later table");Expect(noteReflow,"early semantic edit did not reflow fixture footnote");Expect(pageCountChanged,"early semantic edit did not change paginated page count");Expect(finalHeader.Occurrences==finalFooter.Occurrences&&finalHeader.Occurrences>0,"native header/footer did not repeat on each final page");Expect(basePageField.Page!=finalPageField.Page||pageCountChanged,"page-count field did not observe layout reflow");
var renderEvidence=new{required_mapping_count=requiredIds.Length,retired_fixture_render_exemption=new{object_id=Ids.Lower(decomposedBody),reason="canonical B-T3 split/merge victim; retired source identity is not final render authority"},html_mapping_percent=100,pdf_mapping_percent=100,base_pdf=new{path=Path.GetRelativePath(repo,basePdf.Path).Replace('\\','/'),sha256=basePdf.Sha256,layout_revision=basePdf.LayoutRevision.LayoutRevisionId,pages=baseHeader.Occurrences},final_html=new{path=Path.GetRelativePath(repo,finalHtml.Path).Replace('\\','/'),sha256=finalHtml.Sha256,layout_revision=finalHtml.LayoutRevision.LayoutRevisionId,html_structure_validated=true},final_pdf=new{path=Path.GetRelativePath(repo,finalPdf.Path).Replace('\\','/'),sha256=finalPdf.Sha256,layout_revision=finalPdf.LayoutRevision.LayoutRevisionId,pages=finalHeader.Occurrences,pdf_ua_1=true,provider_source_sha256=finalPdf.ProviderSourceSha256},reflow=new{table=tableReflow,footnote=noteReflow,header_footer_occurrences_changed=pageCountChanged,base_pages=baseHeader.Occurrences,final_pages=finalHeader.Occurrences,page_field_mapped=true}};Pass("B-RENDER",new{required_mapping_percent=100,base_pages=baseHeader.Occurrences,final_pages=finalHeader.Occurrences,table_reflow=tableReflow,footnote_reflow=noteReflow,pdf_ua_1=true,html_structure=true});

int winword=Process.GetProcessesByName("WINWORD").Length;bool winwordExe=new[]{@"C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE",@"C:\Program Files (x86)\Microsoft Office\root\Office16\WINWORD.EXE"}.Any(File.Exists);Expect(winword==0&&!winwordExe,"Word-zero gate failed in semantic B");
var evidence=new{architecture_freeze=DndConstants.ArchitectureFreeze,generated_utc=DateTimeOffset.UtcNow,fixture_root=((JsonDocument.Parse(File.ReadAllText(manifestPath))).RootElement.GetProperty("SemanticRoot").GetString()),initial_revision=Ids.Lower(initialHead.RevisionId),external_revision=Ids.Lower(externalHead.RevisionId),final_revision=Ids.Lower(finalHead.RevisionId),final_root=Convert.ToHexString(finalHead.SemanticRoot).ToLowerInvariant(),transactions=transactionEvidence,checks,render=renderEvidence,word=new{winword_processes=winword,winword_exe_present=winwordExe,com_calls=0,api_calls=0,microsoft_365_trial_started=false},semantic_phase="PASS",render_phase="PASS",result="PASS"};string evidencePath=Path.Combine(repo,"evidence","milestone-b.json");File.WriteAllText(evidencePath,JsonSerializer.Serialize(evidence,new JsonSerializerOptions{WriteIndented=true}),new UTF8Encoding(false));Console.WriteLine("MILESTONE B PASS");Console.WriteLine("EVIDENCE="+evidencePath);
