import { DatabaseSync } from 'node:sqlite';
import { createHash, randomBytes } from 'node:crypto';
import { TextDecoder } from 'node:util';

const DOMAINS=['objects','boundaries','relations','extensions','assets','providers','lifecycle','layout','commit'];
const td=new TextDecoder('utf-8',{fatal:true});
const sha=(...parts)=>{const h=createHash('sha256');for(const p of parts)h.update(p);return h.digest();};
const ascii=s=>Buffer.from(s,'ascii');
const part=b=>{b=Buffer.from(b);const n=Buffer.alloc(4);n.writeInt32BE(b.length);return Buffer.concat([n,b]);};
const keyFor=(kind,id)=>sha(ascii('DOCSeye:DND1:key\0'),ascii(kind),Buffer.from([0]),Buffer.from(id));
const leafHash=(domain,key,value)=>sha(ascii('DOCSeye:DND1:leaf\0'),ascii(domain),Buffer.from([0]),key,sha(value));
const emptyHash=(domain,depth)=>sha(ascii('DOCSeye:DND1:empty\0'),ascii(domain),Buffer.from([0,depth]));
const internalHash=(domain,depth,children)=>{if(children.length===0)return emptyHash(domain,depth);children=[...children].sort((a,b)=>a[0]-b[0]);return sha(ascii('DOCSeye:DND1:node\0'),part(ascii(domain)),Buffer.from([depth]),...children.flatMap(([b,h])=>[Buffer.from([b]),h]));};
function domainRoot(domain,entries){function walk(rows,depth){if(depth===32){if(rows.length!==1)throw new Error('duplicate root key');return leafHash(domain,rows[0].key,rows[0].value);}if(rows.length===0)return emptyHash(domain,depth);const groups=new Map();for(const r of rows){const b=r.key[depth];if(!groups.has(b))groups.set(b,[]);groups.get(b).push(r);}return internalHash(domain,depth,[...groups].map(([b,g])=>[b,walk(g,depth+1)]));}return walk(entries,0);}
function overallRoot(entries){const roots=new Map();for(const d of DOMAINS)roots.set(d,domainRoot(d,entries.filter(e=>e.domain===d)));return sha(ascii('DOCSeye:DND1:semantic-root\0'),...DOMAINS.flatMap(d=>[part(ascii(d)),part(roots.get(d))]));}
function head(major,n){n=BigInt(n);if(n<24n)return Buffer.from([(major<<5)|Number(n)]);if(n<=0xffn)return Buffer.from([(major<<5)|24,Number(n)]);if(n<=0xffffn){const b=Buffer.alloc(3);b[0]=(major<<5)|25;b.writeUInt16BE(Number(n),1);return b;}if(n<=0xffffffffn){const b=Buffer.alloc(5);b[0]=(major<<5)|26;b.writeUInt32BE(Number(n),1);return b;}const b=Buffer.alloc(9);b[0]=(major<<5)|27;b.writeBigUInt64BE(n,1);return b;}
const taggedUuid=b=>({__uuid:Buffer.from(b)});
function cbor(v){if(v===null||v===undefined)return Buffer.from([0xf6]);if(typeof v==='boolean')return Buffer.from([v?0xf5:0xf4]);if(typeof v==='number'){if(!Number.isSafeInteger(v))throw new Error('non-integer canonical number');return v>=0?head(0,v):head(1,-1-v);}if(typeof v==='bigint')return v>=0n?head(0,v):head(1,-1n-v);if(typeof v==='string'){const b=Buffer.from(v,'utf8');return Buffer.concat([head(3,b.length),b]);}if(Buffer.isBuffer(v)||v instanceof Uint8Array){const b=Buffer.from(v);return Buffer.concat([head(2,b.length),b]);}if(v&&v.__uuid){const b=Buffer.from(v.__uuid);if(b.length!==16)throw new Error('uuid length');return Buffer.concat([Buffer.from([0xd8,37]),head(2,16),b]);}if(Array.isArray(v)){const vals=v.map(cbor);return Buffer.concat([head(4,vals.length),...vals]);}if(typeof v==='object'){const pairs=Object.entries(v).map(([k,val])=>{if(!/^[\x00-\x7f]*$/.test(k))throw new Error('non-ascii key');const ek=cbor(k);return[ek,cbor(val)];});pairs.sort((a,b)=>Buffer.compare(a[0],b[0]));return Buffer.concat([head(5,pairs.length),...pairs.flat()]);}throw new Error('unsupported CBOR type');}
function readAi(buf,state,ai){const need=n=>{if(state.p+n>buf.length)throw new Error('truncated');};if(ai<24)return BigInt(ai);if(ai===24){need(1);const v=BigInt(buf[state.p++]);if(v<24n)throw new Error('nonshort');return v;}if(ai===25){need(2);const v=BigInt(buf.readUInt16BE(state.p));state.p+=2;if(v<=0xffn)throw new Error('nonshort');return v;}if(ai===26){need(4);const v=BigInt(buf.readUInt32BE(state.p));state.p+=4;if(v<=0xffffn)throw new Error('nonshort');return v;}if(ai===27){need(8);const v=buf.readBigUInt64BE(state.p);state.p+=8;if(v<=0xffffffffn)throw new Error('nonshort');return v;}if(ai===31)throw new Error('indefinite');throw new Error('reserved additional info');}
function safeNumber(n){return n<=BigInt(Number.MAX_SAFE_INTEGER)?Number(n):n;}
function decodeOne(buf,state,depth=0,limits={entries:0,maxEntries:1000000,maxScalar:64*1024*1024}){if(depth>64){const e=new Error('resource_limit');e.classification='resource_limit';throw e;}if(++limits.entries>limits.maxEntries){const e=new Error('resource_limit');e.classification='resource_limit';throw e;}if(state.p>=buf.length)throw new Error('truncated');const ib=buf[state.p++],major=ib>>5,ai=ib&31;if(major===0){const n=readAi(buf,state,ai);return safeNumber(n);}if(major===1){const n=readAi(buf,state,ai),v=-1n-n;return v>=BigInt(Number.MIN_SAFE_INTEGER)?Number(v):v;}if(major===2||major===3){const n=readAi(buf,state,ai);if(n>BigInt(limits.maxScalar)){const e=new Error('resource_limit');e.classification='resource_limit';throw e;}const len=Number(n);if(state.p+len>buf.length)throw new Error('truncated');const b=buf.subarray(state.p,state.p+len);state.p+=len;if(major===2)return Buffer.from(b);return td.decode(b);}if(major===4){const n=readAi(buf,state,ai);if(n>BigInt(limits.maxEntries)){const e=new Error('resource_limit');e.classification='resource_limit';throw e;}const a=[];for(let i=0;i<Number(n);i++)a.push(decodeOne(buf,state,depth+1,limits));return a;}if(major===5){const n=readAi(buf,state,ai);if(n>BigInt(limits.maxEntries)){const e=new Error('resource_limit');e.classification='resource_limit';throw e;}const o={};let prev=null;for(let i=0;i<Number(n);i++){const ks=state.p,k=decodeOne(buf,state,depth+1,limits),ke=state.p;if(typeof k!=='string'||!/^[\x00-\x7f]*$/.test(k))throw new Error('map key');const enc=buf.subarray(ks,ke);if(prev&&Buffer.compare(prev,enc)>=0)throw new Error('map order/duplicate');prev=Buffer.from(enc);if(Object.prototype.hasOwnProperty.call(o,k))throw new Error('duplicate');o[k]=decodeOne(buf,state,depth+1,limits);}return o;}if(major===6){const tag=readAi(buf,state,ai);if(tag!==37n)throw new Error('unsupported tag');const v=decodeOne(buf,state,depth+1,limits);if(!Buffer.isBuffer(v)||v.length!==16)throw new Error('invalid uuid');return taggedUuid(v);}if(major===7){if(ai===20)return false;if(ai===21)return true;if(ai===22)return null;throw new Error('float/simple forbidden');}throw new Error('major type');}
function decodeCbor(buf){const state={p:0};const v=decodeOne(Buffer.from(buf),state);if(state.p!==buf.length)throw new Error('trailing');return v;}
function classifyCbor(buf){try{decodeCbor(buf);return'valid';}catch(e){return e.classification||'malformed_cbor';}}
function v4bytes(){const b=randomBytes(16);b[6]=(b[6]&0x0f)|0x40;b[8]=(b[8]&0x3f)|0x80;return b;}
function hexUuid(s){const h=s.replaceAll('-','');if(!/^[0-9a-fA-F]{32}$/.test(h))throw new Error('invalid uuid text');return Buffer.from(h,'hex');}
function uuidText(b){const h=Buffer.from(b).toString('hex');return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
function orderBig(b){return Buffer.from(b).readBigUInt64BE(0)*0x10000000000000000n+Buffer.from(b).readBigUInt64BE(8);}
function orderBytes(v){const b=Buffer.alloc(16);b.writeBigUInt64BE(v>>64n,0);b.writeBigUInt64BE(v&0xffffffffffffffffn,8);return b;}
function objectCbor(id,type,parent,role,data,retired=false){return cbor({id:taggedUuid(id),type,parent_id:parent?taggedUuid(parent):null,role:role??null,retired,data});}
function boundaryCbor(row,newOffset=row.scalar_offset,newOwner=Buffer.from(row.owner_id)){return cbor({id:taggedUuid(row.id),owner_id:taggedUuid(newOwner),scalar_offset:Number(newOffset),affinity:row.affinity,state:row.state});}
function retiredCbor(id,resolution,successors,expiry){return cbor({object_id:taggedUuid(id),resolution,successors:successors.map(taggedUuid),expires_after_sequence:expiry});}
function extensionCbor(e){return cbor({extension_id:taggedUuid(e.id),namespace_uri:e.namespace_uri,type_name:e.type_name,major:e.major,minor:e.minor,payload_encoding:e.payload_encoding,exact_payload:e.payload,payload_digest:e.payload_digest,coverage_kind:e.coverage_kind,target_id:e.target_id?taggedUuid(e.target_id):null,property_name:e.property_name??null,start_boundary_id:e.start_boundary_id?taggedUuid(e.start_boundary_id):null,end_boundary_id:e.end_boundary_id?taggedUuid(e.end_boundary_id):null,edit_policy:e.edit_policy,required:!!e.required,fallback:e.fallback??null});}
function upsertRoot(db,domain,key,value){db.prepare('INSERT INTO root_entries(domain,key,value,leaf_hash) VALUES(?,?,?,?) ON CONFLICT(domain,key) DO UPDATE SET value=excluded.value,leaf_hash=excluded.leaf_hash').run(domain,key,value,leafHash(domain,key,value));}
function deleteRoot(db,domain,key){db.prepare('DELETE FROM root_entries WHERE domain=? AND key=?').run(domain,key);}
function rootRows(db){return db.prepare('SELECT domain,key,value FROM root_entries ORDER BY domain,key').all().map(r=>({domain:r.domain,key:Buffer.from(r.key),value:Buffer.from(r.value)}));}
function rebuildRelation(db,parent){if(!parent)return;const rows=db.prepare('SELECT id FROM objects WHERE parent_id=? AND retired=0 ORDER BY order_key,id').all(parent).map(r=>Buffer.from(r.id));const k=keyFor('children',parent);if(rows.length===0){deleteRoot(db,'relations',k);return;}const value=cbor({parent_id:taggedUuid(parent),ordered_child_ids:rows.map(taggedUuid)});upsertRoot(db,'relations',k,value);}
function commitRevision(db,delta){const old=db.prepare('SELECT branch_id,revision_id,sequence FROM head WHERE id=1').get();const root=overallRoot(rootRows(db)),revision=v4bytes(),seq=Number(old.sequence)+1;db.prepare('INSERT INTO revisions(revision_id,branch_id,sequence,semantic_root,parent1,parent2) VALUES(?,?,?,?,?,NULL)').run(revision,old.branch_id,seq,root,old.revision_id);db.prepare('UPDATE head SET revision_id=?,sequence=?,semantic_root=? WHERE id=1').run(revision,seq,root);const deltaBytes=cbor(delta);db.prepare('INSERT OR REPLACE INTO deltas(sequence,from_revision_id,to_revision_id,delta_cbor,acknowledged,expires_after_sequence) VALUES(?,?,?,?,0,?)').run(seq,old.revision_id,revision,deltaBytes,seq+64);return{sequence:seq,revision_id:uuidText(revision),semantic_root:root.toString('hex')};}
function withWrite(dbPath,fn){const db=new DatabaseSync(dbPath,{readOnly:false});db.exec('PRAGMA journal_mode=DELETE; PRAGMA synchronous=FULL; PRAGMA trusted_schema=OFF; BEGIN IMMEDIATE');try{const detail=fn(db),committed=commitRevision(db,detail.delta);db.exec('COMMIT');return{classification:'committed',...committed,...detail.output};}catch(e){try{db.exec('ROLLBACK')}catch{};throw e;}finally{db.close();}}
function moveBoundary(dbPath,idText,delta){return withWrite(dbPath,db=>{const id=hexUuid(idText),row=db.prepare('SELECT id,owner_id,scalar_offset,affinity,state FROM boundaries WHERE id=?').get(id);if(!row)throw new Error('boundary not found');const next=Number(row.scalar_offset)+Number(delta);if(next<0)throw new Error('invalid offset');const b={...row,id:Buffer.from(row.id),owner_id:Buffer.from(row.owner_id)},value=boundaryCbor(b,next);db.prepare('UPDATE boundaries SET scalar_offset=?,cbor=? WHERE id=?').run(next,value,id);upsertRoot(db,'boundaries',keyFor('boundary',id),value);return{delta:{kind:'external_boundary_move',boundary_id:taggedUuid(id),new_offset:next},output:{boundary_id:idText,new_offset:next}};});}
function moveObject(dbPath,idText,newIndex){return withWrite(dbPath,db=>{const id=hexUuid(idText),row=db.prepare('SELECT id,parent_id FROM objects WHERE id=? AND retired=0').get(id);if(!row)throw new Error('object not found');const parent=row.parent_id?Buffer.from(row.parent_id):null;if(!parent)throw new Error('root cannot move');let sib=db.prepare('SELECT id FROM objects WHERE parent_id=? AND retired=0 ORDER BY order_key,id').all(parent).map(r=>Buffer.from(r.id));const old=sib.findIndex(x=>x.equals(id));if(old<0)throw new Error('not sibling');sib.splice(old,1);newIndex=Math.max(0,Math.min(Number(newIndex),sib.length));sib.splice(newIndex,0,id);const step=((1n<<128n)-1n)/BigInt(sib.length+1);for(let i=0;i<sib.length;i++)db.prepare('UPDATE objects SET order_key=? WHERE id=?').run(orderBytes(step*BigInt(i+1)),sib[i]);rebuildRelation(db,parent);return{delta:{kind:'external_move',object_id:taggedUuid(id),new_index:newIndex},output:{object_id:idText,new_index:newIndex}};});}
function splitText(dbPath,idText,splitScalar){return withWrite(dbPath,db=>{const id=hexUuid(idText),row=db.prepare('SELECT id,type,parent_id,order_key,role,cbor FROM objects WHERE id=? AND retired=0').get(id);if(!row||row.type!=='text_block')throw new Error('text block not found');const parsed=decodeCbor(Buffer.from(row.cbor)),text=parsed.data?.text;if(typeof text!=='string')throw new Error('text missing');const scalars=Array.from(text);splitScalar=Number(splitScalar);if(splitScalar<=0||splitScalar>=scalars.length)throw new Error('bad split');const left=v4bytes(),right=v4bytes(),parent=row.parent_id?Buffer.from(row.parent_id):null,base=orderBig(row.order_key);const nextRow=parent?db.prepare('SELECT order_key FROM objects WHERE parent_id=? AND retired=0 AND order_key>? ORDER BY order_key LIMIT 1').get(parent,row.order_key):null;const upper=nextRow?orderBig(nextRow.order_key):((1n<<128n)-1n);if(upper<=base+1n)throw new Error('order space');const rightOrder=base+(upper-base)/2n,ldata={...parsed.data,text:scalars.slice(0,splitScalar).join('')},rdata={...parsed.data,text:scalars.slice(splitScalar).join('')},lc=objectCbor(left,'text_block',parent,row.role,ldata,false),rc=objectCbor(right,'text_block',parent,row.role,rdata,false);db.prepare('UPDATE objects SET retired=1,cbor=? WHERE id=?').run(objectCbor(id,row.type,parent,row.role,parsed.data,true),id);db.prepare('INSERT INTO objects(id,type,parent_id,order_key,role,cbor,retired) VALUES(?,?,?,?,?,?,0)').run(left,'text_block',parent,row.order_key,row.role,lc);db.prepare('INSERT INTO objects(id,type,parent_id,order_key,role,cbor,retired) VALUES(?,?,?,?,?,?,0)').run(right,'text_block',parent,orderBytes(rightOrder),row.role,rc);deleteRoot(db,'objects',keyFor('object',id));upsertRoot(db,'objects',keyFor('object',left),lc);upsertRoot(db,'objects',keyFor('object',right),rc);const bounds=db.prepare('SELECT id,owner_id,scalar_offset,affinity,state FROM boundaries WHERE owner_id=?').all(id);for(const b0 of bounds){const b={...b0,id:Buffer.from(b0.id),owner_id:Buffer.from(b0.owner_id)},pos=Number(b.scalar_offset),goRight=pos>splitScalar,owner=goRight?right:left,off=goRight?pos-splitScalar:pos,bc=boundaryCbor(b,off,owner);db.prepare('UPDATE boundaries SET owner_id=?,scalar_offset=?,cbor=? WHERE id=?').run(owner,off,bc,b.id);upsertRoot(db,'boundaries',keyFor('boundary',b.id),bc);}const oldHead=db.prepare('SELECT sequence FROM head WHERE id=1').get(),expiry=Number(oldHead.sequence)+65,successors=[left,right];db.prepare('INSERT INTO retired_witnesses(object_id,resolution,successors_cbor,expires_after_sequence) VALUES(?,?,?,?)').run(id,'split',cbor(successors.map(taggedUuid)),expiry);upsertRoot(db,'lifecycle',keyFor('retired-object',id),retiredCbor(id,'split',successors,expiry));rebuildRelation(db,parent);return{delta:{kind:'external_split',old_id:taggedUuid(id),left_id:taggedUuid(left),right_id:taggedUuid(right),split_scalar:splitScalar},output:{old_id:idText,left_id:uuidText(left),right_id:uuidText(right)}};});}
function mergeText(dbPath,leftText,rightText){return withWrite(dbPath,db=>{const left=hexUuid(leftText),right=hexUuid(rightText),l=db.prepare('SELECT id,type,parent_id,order_key,role,cbor FROM objects WHERE id=? AND retired=0').get(left),r=db.prepare('SELECT id,type,parent_id,order_key,role,cbor FROM objects WHERE id=? AND retired=0').get(right);if(!l||!r||l.type!=='text_block'||r.type!=='text_block'||!Buffer.from(l.parent_id??[]).equals(Buffer.from(r.parent_id??[])))throw new Error('merge targets');const ld=decodeCbor(Buffer.from(l.cbor)),rd=decodeCbor(Buffer.from(r.cbor)),lt=ld.data?.text,rt=rd.data?.text;if(typeof lt!=='string'||typeof rt!=='string')throw new Error('merge text missing');const result=v4bytes(),parent=l.parent_id?Buffer.from(l.parent_id):null,data={...ld.data,text:lt+rt},cc=objectCbor(result,'text_block',parent,l.role,data,false);db.prepare('UPDATE objects SET retired=1,cbor=? WHERE id=?').run(objectCbor(left,l.type,parent,l.role,ld.data,true),left);db.prepare('UPDATE objects SET retired=1,cbor=? WHERE id=?').run(objectCbor(right,r.type,parent,r.role,rd.data,true),right);db.prepare('INSERT INTO objects(id,type,parent_id,order_key,role,cbor,retired) VALUES(?,?,?,?,?,?,0)').run(result,'text_block',parent,l.order_key,l.role,cc);deleteRoot(db,'objects',keyFor('object',left));deleteRoot(db,'objects',keyFor('object',right));upsertRoot(db,'objects',keyFor('object',result),cc);const leftLen=Array.from(lt).length;for(const source of [left,right]){const bounds=db.prepare('SELECT id,owner_id,scalar_offset,affinity,state FROM boundaries WHERE owner_id=?').all(source);for(const b0 of bounds){const b={...b0,id:Buffer.from(b0.id),owner_id:Buffer.from(b0.owner_id)},off=Number(b.scalar_offset)+(source.equals(right)?leftLen:0),bc=boundaryCbor(b,off,result);db.prepare('UPDATE boundaries SET owner_id=?,scalar_offset=?,cbor=? WHERE id=?').run(result,off,bc,b.id);upsertRoot(db,'boundaries',keyFor('boundary',b.id),bc);}}const oldHead=db.prepare('SELECT sequence FROM head WHERE id=1').get(),expiry=Number(oldHead.sequence)+65;for(const source of [left,right]){db.prepare('INSERT INTO retired_witnesses(object_id,resolution,successors_cbor,expires_after_sequence) VALUES(?,?,?,?)').run(source,'merged',cbor([taggedUuid(result)]),expiry);upsertRoot(db,'lifecycle',keyFor('retired-object',source),retiredCbor(source,'merged',[result],expiry));}rebuildRelation(db,parent);return{delta:{kind:'external_merge',left_id:taggedUuid(left),right_id:taggedUuid(right),result_id:taggedUuid(result)},output:{left_id:leftText,right_id:rightText,result_id:uuidText(result)}};});}
function addExtension(dbPath,targetText){return withWrite(dbPath,db=>{const target=hexUuid(targetText);if(!db.prepare('SELECT 1 FROM objects WHERE id=? AND retired=0').get(target))throw new Error('target missing');const id=v4bytes(),payload=Buffer.from('independent-public-spec-extension\0exact','utf8'),digest=sha(payload),e={id,namespace_uri:'urn:docseye:independent:e08',type_name:'oracle_extension',major:1,minor:0,payload_encoding:'bytes',payload,payload_digest:digest,coverage_kind:'object',target_id:target,property_name:null,start_boundary_id:null,end_boundary_id:null,edit_policy:'independent',required:false,fallback:null},ec=extensionCbor(e);db.prepare('INSERT INTO extensions(id,namespace_uri,type_name,major,minor,payload_encoding,payload,payload_digest,coverage_kind,target_id,property_name,start_boundary_id,end_boundary_id,edit_policy,required,fallback,cbor) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,e.namespace_uri,e.type_name,e.major,e.minor,e.payload_encoding,payload,digest,e.coverage_kind,target,null,null,null,e.edit_policy,0,null,ec);upsertRoot(db,'extensions',keyFor('extension',id),ec);return{delta:{kind:'external_extension_add',extension_id:taggedUuid(id),target_id:taggedUuid(target)},output:{extension_id:uuidText(id),target_id:targetText,payload_digest:digest.toString('hex')}};});}
function rootCommand(dbPath){const db=new DatabaseSync(dbPath,{readOnly:true});try{console.log(overallRoot(rootRows(db)).toString('hex'));}finally{db.close();}}
function cborSuite(){const uuid=Buffer.from('00112233445546778899aabbccddeeff','hex'),vectors={simple_map:{a:1,z:'e\u0301',uuid:taggedUuid(uuid),bytes:Buffer.from('00ff10','hex')},signed:[-1,-24,-25,0,23,24,255,256,65535,65536],nested:{alpha:[true,false,null,'x'],beta:{a:1,b:2}},uuid:taggedUuid(uuid),text:'A\u030A \u65E5\u672C \u0645\u0631\u062D\u0628\u0627',bytes:Buffer.from('000102feff','hex'),extension:{extension_id:taggedUuid(uuid),namespace_uri:'urn:test',type_name:'x',major:1,minor:0,payload_encoding:'bytes',exact_payload:Buffer.from('abc'),payload_digest:sha(Buffer.from('abc')),coverage_kind:'object',target_id:null,property_name:null,start_boundary_id:null,end_boundary_id:null,edit_policy:'independent',required:false,fallback:null}};const out={};for(const[k,v]of Object.entries(vectors))out[k]=cbor(v).toString('hex');console.log(JSON.stringify(out));}
const [cmd,...args]=process.argv.slice(2);try{let result;if(cmd==='move-boundary')result=moveBoundary(args[0],args[1],Number(args[2]));else if(cmd==='move-object')result=moveObject(args[0],args[1],Number(args[2]));else if(cmd==='split-text')result=splitText(args[0],args[1],Number(args[2]));else if(cmd==='merge-text')result=mergeText(args[0],args[1],args[2]);else if(cmd==='add-extension')result=addExtension(args[0],args[1]);else if(cmd==='root'){rootCommand(args[0]);process.exit(0);}else if(cmd==='cbor-suite'){cborSuite();process.exit(0);}else if(cmd==='validate-hex'){console.log(classifyCbor(Buffer.from(args[0],'hex')));process.exit(0);}else throw new Error(`unknown command ${cmd}`);console.log(JSON.stringify(result));}catch(e){console.error(e.stack||e);process.exit(1);}