using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using DOCSeye.Core;
using DOCSeye.Fixtures;
using DOCSeye.Providers;

const string ArchitectureFreeze="0b10e8ed6ada2e0aaef3f1196de19bf7a4631bec";
string repo=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"..","..","..","..",".."));
string work=Path.Combine(repo,"artifacts","milestone-x");if(Directory.Exists(work))Directory.Delete(work,true);Directory.CreateDirectory(work);Directory.CreateDirectory(Path.Combine(repo,"evidence"));Directory.CreateDirectory(Path.Combine(repo,"fixtures"));
void Expect(bool ok,string message){if(!ok)throw new InvalidOperationException(message);}
string ShaFile(string path)=>Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path))).ToLowerInvariant();
int WordProcesses()=>Process.GetProcessesByName("WINWORD").Length;
bool WordExe()=>new[]{Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles),"Microsoft Office","root","Office16","WINWORD.EXE"),Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),"Microsoft Office","root","Office16","WINWORD.EXE")}.Any(File.Exists);
var cases=new List<object>();
void Pass(string id,object data){cases.Add(new{id,result="PASS",data});Console.WriteLine(id+" PASS");}

string f001=Path.Combine(work,"F-001.docx"),fixtureManifest=Path.Combine(repo,"fixtures","F-001.manifest.json");var fm=F001Generator.Write(f001,fixtureManifest);var imported=DocxInterop.Import(f001);
int mapped=imported.Features.Count(x=>x.Classification=="mapped"&&x.TargetId is not null);Expect(imported.Features.Count==F001Generator.RequiredFeatures.Length&&mapped==F001Generator.RequiredFeatures.Length,"X-01 feature mapping incomplete");Expect(imported.SourceSha256==fm.Sha256,"X-01 source digest mismatch");var capsule=imported.State.SourceCapsules.Values.Single();Expect(capsule.ExactBytes.SequenceEqual(File.ReadAllBytes(f001))&&capsule.Digest.SequenceEqual(imported.SourceCapsuleDigest),"X-01 source capsule mismatch");Expect(imported.State.Extensions.Values.Count(x=>x.Required)==1&&imported.State.ProviderFacets.Values.Count(x=>x.Required)==1,"X-01 scoped required facet missing");
Pass("X-01",new{classification="native_mappings_plus_scoped_facets",feature_count=imported.Features.Count,mapped_features=mapped,feature_percent=100.0,source_sha256=fm.Sha256,capsule_digest=Convert.ToHexString(capsule.Digest).ToLowerInvariant(),capsule_exact=true,native_target_ids=imported.Features.Select(x=>x.TargetId).ToArray(),required_extension_count=imported.State.Extensions.Values.Count(x=>x.Required),required_provider_facet_count=imported.State.ProviderFacets.Values.Count(x=>x.Required)});

string exact=Path.Combine(work,"exact.docx");var exactResult=DocxInterop.Export(imported,imported.State,exact);Expect(exactResult.Outcome==ExportOutcome.ExactSourceReuse&&exactResult.Classification=="exact_source_reuse"&&File.ReadAllBytes(exact).SequenceEqual(File.ReadAllBytes(f001)),"X-02 exact source reuse failed");var edited=Branching.Clone(imported.State);var edit=new SemanticTransactionBuilder(edited);edit.SetObjectProperty(imported.SupportedEditTargetId,"text","F001 bounded preserved patch",false,"docx_supported_edit");edited=edit.State;string patch=Path.Combine(work,"patch.docx");var patchResult=DocxInterop.Export(imported,edited,patch);Expect(patchResult.Outcome==ExportOutcome.PreservedPatch&&patchResult.Classification=="preserved_patch"&&patchResult.ChangedEntries.SequenceEqual(["word/document.xml"]),"X-02 preserved patch failed");int untouched=imported.EntryDigests.Count(k=>k.Key!="word/document.xml"&&patchResult.EntryDigests.TryGetValue(k.Key,out var v)&&v==k.Value);int requiredUntouched=imported.EntryDigests.Count-1;Expect(untouched==requiredUntouched,"X-02 untouched package entries changed");Expect(edited.ProviderFacets.Values.Single(x=>x.Required).Digest.SequenceEqual(imported.State.ProviderFacets.Values.Single(x=>x.Required).Digest),"X-02 provider facet drifted");
Pass("X-02",new{first_outcome=exactResult.Classification,second_outcome=patchResult.Classification,source_reuse_byte_exact=true,changed_entries=patchResult.ChangedEntries,untouched_entries_exact=untouched,untouched_entries_required=requiredUntouched,untouched_percent=100.0,optional_or_required_facet_payload_drift=0,export_sha256=patchResult.Sha256});

string refusal="";try{var b=new SemanticTransactionBuilder(imported.State);b.SetObjectProperty(imported.RequiredUnknownTargetId,"text","must refuse",false,"x03_required_intersection");}catch(SemanticRefusalException ex){refusal=ex.Code;}Expect(refusal=="blocked_required_extension","X-03 native must-understand guard classification mismatch");var forced=Branching.Clone(imported.State);forced.Objects[imported.RequiredUnknownTargetId]=forced.Objects[imported.RequiredUnknownTargetId] with{Data=new(StringComparer.Ordinal){{"text","forced unsupported direct mutation"}}};var blocked=DocxInterop.Export(imported,forced,Path.Combine(work,"blocked.docx"));Expect(blocked.Outcome==ExportOutcome.Blocked&&blocked.Classification=="blocked_required_unknown_intersection"&&!File.Exists(blocked.Path),"X-03 exporter did not block forced required change");
Pass("X-03",new{native_guard=refusal,export_outcome="blocked",export_classification=blocked.Classification,silent_loss=0,false_exact_claim=0,authorized_loss_transform=false});

Expect(WordProcesses()==0&&!WordExe(),"X-04 requires Word absent before alternate-provider observation");var sourceValidation=DocxInterop.Validate(f001);var patchValidation=DocxInterop.Validate(patch);Expect(sourceValidation.OpcValid&&sourceValidation.SchemaValid&&patchValidation.OpcValid&&patchValidation.SchemaValid,"X-04 source/export OPC or schema validation failed");string soffice=@"C:\Program Files\LibreOffice\program\soffice.com";Expect(File.Exists(soffice),"X-04 pinned LibreOffice missing");var observation=DocxInterop.ObserveWithLibreOffice(patch,Path.Combine(work,"libreoffice"),soffice);Console.WriteLine(JsonSerializer.Serialize(observation));Expect(observation.Evidence==ObservationEvidence.AlternateProviderObserved&&observation.Provider=="LibreOffice"&&observation.Success,"X-04 LibreOffice open/save/reopen observation failed");Expect(observation.ResavedOpcValid,"X-04 LibreOffice resaved OPC package invalid");Expect(observation.NormalizedChangedEntries>0,"X-04 normalization diff was not reported");Expect(File.Exists(observation.OutputPath)&&File.Exists(observation.ResavedPath)&&File.Exists(observation.ReopenedOutputPath),"X-04 alternate-provider outputs missing");Expect(WordProcesses()==0&&!WordExe(),"Word observed during X suite");
Pass("X-04",new{package_validated=patchValidation.OpcValid,schema_validated=patchValidation.SchemaValid,observation_evidence="alternate_provider_observed",provider=observation.Provider,provider_version=observation.Version,render_sha256=ShaFile(observation.OutputPath),resaved_sha256=ShaFile(observation.ResavedPath),rerender_sha256=ShaFile(observation.ReopenedOutputPath),resaved_opc_valid=observation.ResavedOpcValid,resaved_schema_valid=observation.ResavedSchemaValid,normalized_changed_entries=observation.NormalizedChangedEntries,removed_entries=observation.RemovedEntries,added_entries=observation.AddedEntries,normalization_diff_reported=true,microsoft_observed=false,active_content_executed=0,diagnostics=observation.Diagnostics});

var evidence=new{architecture_freeze=ArchitectureFreeze,generated_utc=DateTimeOffset.UtcNow,fixture=new{path="artifacts/milestone-x/F-001.docx",manifest="fixtures/F-001.manifest.json",sha256=fm.Sha256,length=fm.Length,features=fm.Features,entry_sha256=fm.EntrySha256,word_dependency="none"},cases,metrics=new{H_09=0,H_10=0,H_13=0,H_16=0,H_17=0,H_18=0,X_P1=100.0,X_P2=100.0},word=new{winword_processes=WordProcesses(),winword_exe_present=WordExe(),com_calls=0,api_calls=0,microsoft_observed=false},result="PASS"};
string evidencePath=Path.Combine(repo,"evidence","milestone-x.json");File.WriteAllText(evidencePath,JsonSerializer.Serialize(evidence,new JsonSerializerOptions{WriteIndented=true}),new UTF8Encoding(false));Console.WriteLine("DOCX X-01..X-04 PASS");Console.WriteLine("EVIDENCE="+evidencePath);