using System.Diagnostics;
using System.Text.Json;
using DOCSeye.Fixtures;

string repo=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"..","..","..","..",".."));
string work=Path.Combine(repo,"artifacts","milestone-d");if(Directory.Exists(work))Directory.Delete(work,true);Directory.CreateDirectory(work);Directory.CreateDirectory(Path.Combine(repo,"evidence"));
string dnd=Path.Combine(work,"N-001.dnd"),manifest=Path.Combine(work,"N-001.manifest.json"),evidence=Path.Combine(repo,"evidence","milestone-d.json");N001Generator.Write(dnd,manifest);if(File.Exists(evidence))File.Delete(evidence);
string pipe="docseye-d-"+Environment.ProcessId+"-"+Guid.NewGuid().ToString("N");
string kernel=Path.Combine(repo,"src","DOCSeye.Kernel","bin","Debug","net10.0","DOCSeye.Kernel.exe");
string node=@"C:\AgentBrowser\tools\node-v24.18.1-win-x64\node.exe";
string driver=Path.Combine(repo,"tools","program-host","program-host.mjs"),writer=Path.Combine(repo,"tools","independent-writer","independent-writer.mjs");
string typst=Path.Combine(repo,".tools","typst","typst-x86_64-pc-windows-msvc","typst.exe"),vera=Path.Combine(repo,".tools","verapdf","verapdf.bat"),java=Path.Combine(repo,".tools","java","jdk-25.0.4+7-jre"),figure=Path.Combine(repo,"tests","render","semantic-figure.svg");
foreach(string required in new[]{kernel,node,driver,writer,typst,vera,figure})if(!File.Exists(required))throw new InvalidOperationException("D dependency missing: "+required);if(!Directory.Exists(java))throw new InvalidOperationException("D Java missing: "+java);
var kpsi=new ProcessStartInfo(kernel){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true};kpsi.Environment["DOCSEYE_PIPE"]=pipe;kpsi.Environment["PATH"]=Path.Combine(repo,".tools","sqlite-native")+Path.PathSeparator+Environment.GetEnvironmentVariable("PATH");using var kp=Process.Start(kpsi)??throw new InvalidOperationException("kernel start failed");var kout=kp.StandardOutput.ReadToEndAsync();var kerr=kp.StandardError.ReadToEndAsync();
try
{
    var psi=new ProcessStartInfo(node){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true};foreach(string arg in new[]{driver,pipe,dnd,manifest,work,evidence,typst,vera,java,figure,writer})psi.ArgumentList.Add(arg);using var np=Process.Start(psi)??throw new InvalidOperationException("Node Program Host start failed");var stdoutTask=np.StandardOutput.ReadToEndAsync();var stderrTask=np.StandardError.ReadToEndAsync();if(!np.WaitForExit(300000)){try{np.Kill(true);}catch{}throw new TimeoutException("Node Program Host timeout");}Task.WaitAll(stdoutTask,stderrTask);string stdout=stdoutTask.Result,stderr=stderrTask.Result;if(np.ExitCode!=0)throw new InvalidOperationException("Node Program Host failed: "+stderr+"\n"+stdout);string last=stdout.Split(new[]{'\r','\n'},StringSplitOptions.RemoveEmptyEntries).Last();using var result=JsonDocument.Parse(last);if(result.RootElement.GetProperty("classification").GetString()!="PASS"||result.RootElement.GetProperty("callCount").GetInt32()!=96)throw new InvalidOperationException("Node Program Host result mismatch");if(!File.Exists(evidence))throw new InvalidOperationException("Milestone D evidence missing");using var ev=JsonDocument.Parse(File.ReadAllText(evidence));var root=ev.RootElement;if(root.GetProperty("result").GetString()!="PASS")throw new InvalidOperationException("Milestone D evidence not PASS");var inv=root.GetProperty("invocation");if(inv.GetProperty("total_calls").GetInt32()!=96||inv.GetProperty("material_renders").GetInt32()!=2||inv.GetProperty("material_docx_exports").GetInt32()!=1||inv.GetProperty("intermediate_model_calls").GetInt32()!=0)throw new InvalidOperationException("Milestone D invocation metrics mismatch");var mutations=root.GetProperty("mutations");if(mutations.GetProperty("requested").GetInt32()!=48||mutations.GetProperty("delta_covered").GetInt32()!=48||mutations.GetProperty("unique").GetInt32()!=48)throw new InvalidOperationException("Milestone D mutation coverage mismatch");foreach(var h in root.GetProperty("hard_zero").EnumerateObject())if(h.Value.GetInt32()!=0)throw new InvalidOperationException(h.Name+" nonzero");if(root.GetProperty("word").GetProperty("winword_processes").GetInt32()!=0||root.GetProperty("word").GetProperty("winword_exe_present").GetBoolean())throw new InvalidOperationException("Milestone D Word-zero failed");Console.WriteLine("MILESTONE D PASS 96/96");Console.WriteLine("EVIDENCE="+evidence);Console.WriteLine(last);
}
finally{try{if(!kp.HasExited)kp.Kill(true);}catch{}try{kp.WaitForExit(5000);}catch{} }
