using System.Diagnostics;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using DOCSeye.Core;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Validation;

namespace DOCSeye.Providers;

public sealed record DocxFeatureClassification(string Feature,string Classification,Guid? TargetId,string? Entry,string? Detail=null);
public sealed record DocxImportResult(SemanticState State,SemanticState Baseline,byte[] SourceBytes,string SourceSha256,byte[] SourceCapsuleDigest,IReadOnlyList<DocxFeatureClassification> Features,Guid SupportedEditTargetId,Guid RequiredUnknownTargetId,IReadOnlyDictionary<string,string> EntryDigests);
public sealed record DocxExportResult(ExportOutcome Outcome,string Classification,string Path,string Sha256,IReadOnlyDictionary<string,string> EntryDigests,IReadOnlyList<string> ChangedEntries,IReadOnlyList<string> Diagnostics);
public sealed record DocxValidationResult(bool OpcValid,bool SchemaValid,int ErrorCount,IReadOnlyList<string> Errors,IReadOnlyDictionary<string,string> EntryDigests);
public sealed record DocxObservationResult(ObservationEvidence Evidence,string Provider,string Version,string OutputPath,bool Success,IReadOnlyList<string> Diagnostics,string ResavedPath,string ReopenedOutputPath,bool ResavedOpcValid,bool ResavedSchemaValid,int NormalizedChangedEntries,IReadOnlyList<string> RemovedEntries,IReadOnlyList<string> AddedEntries);

public static class DocxInterop
{
    public static readonly string[] RequiredFeatures =
    [
        "headings_styles","nested_restarted_numbering","merged_table","nested_table","comments_replies","tracked_insert","tracked_delete","tracked_move","tracked_style_change","metadata_field","cross_reference_field","page_field","text_content_control","enum_content_control","bookmarks_internal_refs","section_header_footer","footnote","endnote","figure_media","omml","custom_xml","alternate_content","unknown_mc","opaque_custom_part","inert_opaque_binary"
    ];

    public static DocxImportResult Import(string path)
    {
        byte[] source=File.ReadAllBytes(path);byte[] sourceDigest=SHA256.HashData(source);var entries=ReadEntries(source);string document=Utf8(entries,"word/document.xml");string rels=Utf8(entries,"word/_rels/document.xml.rels");
        var state=new SemanticState{FamilyId=Ids.NewV4(),BranchId=Ids.NewV4(),RevisionId=Ids.NewV4(),Sequence=0,Mode=AuthorityMode.ConvertedImported};Guid root=Ids.NewV4(),flow=Ids.NewV4();state.Objects[root]=new(root,"document",null,OrderKey.Initial(0),"document",new(StringComparer.Ordinal){{"title","F-001 converted import"},{"source_provider","docx"}});state.Objects[flow]=new(flow,"flow",root,OrderKey.Initial(0),"main",new(StringComparer.Ordinal){{"kind","main"}});
        int ordinal=0;Guid Add(string type,string role,Dictionary<string,object?> data){Guid id=Ids.NewV4();state.Objects[id]=new(id,type,flow,OrderKey.Initial(ordinal++),role,data);return id;}
        Guid supported=Add("text_block","body",new(StringComparer.Ordinal){{"text",ExtractSupportedTarget(document)},{"interop_feature","supported_edit_target"},{"source_entry","word/document.xml"}});
        Guid requiredUnknown=Add("interop_unknown","provider_required",new(StringComparer.Ordinal){{"text","unknown required provider meaning"},{"interop_feature","unknown_mc"},{"fallback","Static compatible fallback"},{"source_entry","word/document.xml"}});
        var featureTargets=new Dictionary<string,Guid>(StringComparer.Ordinal){{"unknown_mc",requiredUnknown}};var classifications=new List<DocxFeatureClassification>();
        foreach(string feature in RequiredFeatures)
        {
            bool present=Detect(feature,entries,document,rels);Guid target=featureTargets.TryGetValue(feature,out var mapped)?mapped:Add("interop_feature",feature,new(StringComparer.Ordinal){{"feature",feature},{"classification",present?"mapped":"missing"}});classifications.Add(new(feature,present?"mapped":"missing",target,FeatureEntry(feature),present?null:"required feature not detected"));
        }
        if(classifications.Any(f=>f.Classification!="mapped"))throw new InvalidDataException("F-001 feature classification incomplete: "+string.Join(',',classifications.Where(f=>f.Classification!="mapped").Select(f=>f.Feature)));
        byte[] unknownPayload=Encoding.UTF8.GetBytes(ExtractUnknownChoice(document));Guid extensionId=Ids.NewV4();state.Extensions[extensionId]=new(extensionId,"urn:docseye:docx:mc","required_unknown_choice",1,0,"utf8-xml",unknownPayload,SHA256.HashData(unknownPayload),ExtensionCoverageKind.Object,requiredUnknown,null,null,null,ExtensionEditPolicy.MustUnderstandBeforeEdit,true,"Static compatible fallback");
        Guid facetId=Ids.NewV4();state.ProviderFacets[facetId]=new(facetId,"docx","unknown_mc",requiredUnknown,ExtensionCoverageKind.Object,ExtensionEditPolicy.MustUnderstandBeforeEdit,unknownPayload,SHA256.HashData(unknownPayload),"exact_source",true);
        state.SourceCapsules[Convert.ToHexString(sourceDigest)]=new("docx",source.ToArray(),sourceDigest.ToArray(),"exact_source");var baseline=Branching.Clone(state);return new(state,baseline,source,Convert.ToHexString(sourceDigest).ToLowerInvariant(),sourceDigest,classifications,supported,requiredUnknown,EntryDigests(entries));
    }

    public static DocxExportResult Export(DocxImportResult import,SemanticState current,string outputPath)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);var baseline=import.Baseline;
        if(CanonicalCbor.EncodeObject(current.Objects[import.RequiredUnknownTargetId]).SequenceEqual(CanonicalCbor.EncodeObject(baseline.Objects[import.RequiredUnknownTargetId])) is false)return Blocked("blocked_required_unknown_intersection","required unknown provider target changed");
        if(current.ComputeRoot().SequenceEqual(baseline.ComputeRoot())){File.WriteAllBytes(outputPath,import.SourceBytes);var exact=ReadEntries(import.SourceBytes);return new(ExportOutcome.ExactSourceReuse,"exact_source_reuse",outputPath,HashFile(outputPath),EntryDigests(exact),[],[]);}
        var normalized=Branching.Clone(current);if(!normalized.Objects.ContainsKey(import.SupportedEditTargetId))return Blocked("unsupported","supported edit target removed");normalized.Objects[import.SupportedEditTargetId]=baseline.Objects[import.SupportedEditTargetId];if(!normalized.ComputeRoot().SequenceEqual(baseline.ComputeRoot()))return Blocked("unsupported","semantic changes exceed bounded preserved-patch contract");
        string replacement=current.Objects[import.SupportedEditTargetId].Data.GetValueOrDefault("text") as string??string.Empty;var sourceEntries=ReadEntries(import.SourceBytes);var patched=new SortedDictionary<string,byte[]>(sourceEntries,StringComparer.Ordinal);string document=Utf8(sourceEntries,"word/document.xml");if(!document.Contains("F001_SUPPORTED_EDIT_TARGET",StringComparison.Ordinal))return Blocked("unsupported","supported source marker missing");patched["word/document.xml"]=Encoding.UTF8.GetBytes(document.Replace("F001_SUPPORTED_EDIT_TARGET",XmlEscape(replacement),StringComparison.Ordinal));WriteEntries(outputPath,patched);var digests=EntryDigests(patched);var changed=sourceEntries.Keys.Where(k=>!sourceEntries[k].SequenceEqual(patched[k])).ToArray();if(!changed.SequenceEqual(["word/document.xml"]))return Blocked("preservation_failure","bounded patch changed unexpected entries");return new(ExportOutcome.PreservedPatch,"preserved_patch",outputPath,HashFile(outputPath),digests,changed,[]);
        DocxExportResult Blocked(string classification,string diagnostic)=>new(ExportOutcome.Blocked,classification,outputPath,"",new Dictionary<string,string>(),[],[diagnostic]);
    }

    public static DocxValidationResult Validate(string path)
    {
        var errors=new List<string>();IReadOnlyDictionary<string,string> digests=new Dictionary<string,string>();bool opc=false,schema=false;
        try{byte[] bytes=File.ReadAllBytes(path);var entries=ReadEntries(bytes);digests=EntryDigests(entries);foreach(string required in new[]{"[Content_Types].xml","_rels/.rels","word/document.xml","word/_rels/document.xml.rels"})if(!entries.ContainsKey(required))errors.Add("missing:"+required);ValidateRelationships(entries,errors);opc=errors.Count==0;}catch(Exception ex){errors.Add("opc:"+ex.GetType().Name+":"+ex.Message);}
        try{using var doc=WordprocessingDocument.Open(path,false);var validator=new OpenXmlValidator(FileFormatVersions.Office2013);var validation=validator.Validate(doc).Take(200).ToArray();foreach(var e in validation)errors.Add("schema:"+e.Description+" @ "+e.Path?.XPath);schema=validation.Length==0;}catch(Exception ex){errors.Add("schema_open:"+ex.GetType().Name+":"+ex.Message);}
        return new(opc,schema,errors.Count,errors,digests);
    }

    public static DocxObservationResult ObserveWithLibreOffice(string path,string outputDir,string sofficeExe)
    {
        Directory.CreateDirectory(outputDir);string consoleExe=Path.ChangeExtension(sofficeExe,".com");if(File.Exists(consoleExe))sofficeExe=consoleExe;
        string profile=Path.Combine(outputDir,"profile"),renderDir=Path.Combine(outputDir,"render"),resaveDir=Path.Combine(outputDir,"resave"),rerenderDir=Path.Combine(outputDir,"rerender");foreach(string dir in new[]{profile,renderDir,resaveDir,rerenderDir})Directory.CreateDirectory(dir);
        string profileUri=new Uri(Path.GetFullPath(profile)+Path.DirectorySeparatorChar).AbsoluteUri.TrimEnd('/');string userInstallation="-env:UserInstallation="+profileUri;string[] Prefix()=>["--headless","--nologo","--nodefault","--nofirststartwizard",userInstallation];
        var versionRun=Run(sofficeExe,["--version"],30000);string version=versionRun.stdout.Trim();string stem=Path.GetFileNameWithoutExtension(path);var render=Run(sofficeExe,[..Prefix(),"--convert-to","pdf","--outdir",renderDir,path],90000);string pdf=Path.Combine(renderDir,stem+".pdf");
        var resave=Run(sofficeExe,[..Prefix(),"--convert-to","docx:Office Open XML Text","--outdir",resaveDir,path],90000);string resaved=Path.Combine(resaveDir,stem+".docx");DocxValidationResult validation=File.Exists(resaved)?Validate(resaved):new(false,false,1,["resaved package missing"],new Dictionary<string,string>());var rerender=File.Exists(resaved)?Run(sofficeExe,[..Prefix(),"--convert-to","pdf","--outdir",rerenderDir,resaved],90000):(exitCode:-1,stdout:"",stderr:"resaved package missing");string rerendered=Path.Combine(rerenderDir,stem+".pdf");
        var before=ReadEntryDigests(path);var after=File.Exists(resaved)?ReadEntryDigests(resaved):new Dictionary<string,string>();string[] removed=before.Keys.Except(after.Keys,StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray(),added=after.Keys.Except(before.Keys,StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray();int normalized=before.Keys.Union(after.Keys,StringComparer.Ordinal).Count(k=>!before.TryGetValue(k,out var a)||!after.TryGetValue(k,out var b)||a!=b);
        var diagnostics=new List<string>();void Capture(string phase,(int exitCode,string stdout,string stderr) r){if(r.exitCode!=0)diagnostics.Add(phase+":exit="+r.exitCode);if(!string.IsNullOrWhiteSpace(r.stderr))diagnostics.Add(phase+":stderr="+r.stderr.Trim());if(!string.IsNullOrWhiteSpace(r.stdout))diagnostics.Add(phase+":stdout="+r.stdout.Trim());}Capture("render",render);Capture("resave",resave);Capture("rerender",rerender);diagnostics.AddRange(validation.Errors.Select(x=>"resave_validation:"+x));diagnostics.Add("normalization_removed="+string.Join(',',removed));diagnostics.Add("normalization_added="+string.Join(',',added));diagnostics.Add("normalization_changed_entries="+normalized);
        bool success=render.exitCode==0&&File.Exists(pdf)&&new FileInfo(pdf).Length>0&&resave.exitCode==0&&File.Exists(resaved)&&validation.OpcValid&&rerender.exitCode==0&&File.Exists(rerendered)&&new FileInfo(rerendered).Length>0;
        return new(ObservationEvidence.AlternateProviderObserved,"LibreOffice",version,pdf,success,diagnostics,resaved,rerendered,validation.OpcValid,validation.SchemaValid,normalized,removed,added);
    }
public static IReadOnlyDictionary<string,string> ReadEntryDigests(string path)=>EntryDigests(ReadEntries(File.ReadAllBytes(path)));

    private static bool Detect(string feature,IReadOnlyDictionary<string,byte[]> e,string d,string rels)=>feature switch
    {
        "headings_styles"=>d.Contains("w:pStyle w:val=\"Heading1\"",StringComparison.Ordinal)&&e.ContainsKey("word/styles.xml"),
        "nested_restarted_numbering"=>d.Contains("w:ilvl w:val=\"1\"",StringComparison.Ordinal)&&Utf8(e,"word/numbering.xml").Contains("w:startOverride w:val=\"3\"",StringComparison.Ordinal),
        "merged_table"=>d.Contains("w:gridSpan",StringComparison.Ordinal)&&d.Contains("w:vMerge",StringComparison.Ordinal),"nested_table"=>Regex.Matches(d,"<w:tbl>").Count>=2,
        "comments_replies"=>e.ContainsKey("word/comments.xml")&&e.ContainsKey("word/commentsExtended.xml")&&Utf8(e,"word/commentsExtended.xml").Contains("paraIdParent",StringComparison.Ordinal),
        "tracked_insert"=>d.Contains("<w:ins ",StringComparison.Ordinal),"tracked_delete"=>d.Contains("<w:del ",StringComparison.Ordinal),"tracked_move"=>d.Contains("<w:moveFrom ",StringComparison.Ordinal)&&d.Contains("<w:moveTo ",StringComparison.Ordinal),"tracked_style_change"=>d.Contains("w:pPrChange",StringComparison.Ordinal),
        "metadata_field"=>d.Contains("DOCPROPERTY Title",StringComparison.Ordinal),"cross_reference_field"=>d.Contains(" REF targetBookmark ",StringComparison.Ordinal),"page_field"=>d.Contains(" PAGE ",StringComparison.Ordinal)||Utf8(e,"word/footer1.xml").Contains(" PAGE ",StringComparison.Ordinal),
        "text_content_control"=>d.Contains("w:tag w:val=\"text-control\"",StringComparison.Ordinal),"enum_content_control"=>d.Contains("w:dropDownList",StringComparison.Ordinal),"bookmarks_internal_refs"=>d.Contains("w:bookmarkStart",StringComparison.Ordinal)&&d.Contains("w:hyperlink w:anchor",StringComparison.Ordinal),
        "section_header_footer"=>d.Contains("w:headerReference",StringComparison.Ordinal)&&d.Contains("w:footerReference",StringComparison.Ordinal)&&e.ContainsKey("word/header1.xml")&&e.ContainsKey("word/footer1.xml"),"footnote"=>d.Contains("w:footnoteReference",StringComparison.Ordinal)&&e.ContainsKey("word/footnotes.xml"),"endnote"=>d.Contains("w:endnoteReference",StringComparison.Ordinal)&&e.ContainsKey("word/endnotes.xml"),
        "figure_media"=>rels.Contains("relationships/image",StringComparison.Ordinal)&&e.ContainsKey("word/media/image1.png"),"omml"=>d.Contains("<m:oMath",StringComparison.Ordinal),"custom_xml"=>e.ContainsKey("customXml/item1.xml")&&rels.Contains("relationships/customXml",StringComparison.Ordinal),"alternate_content"=>d.Contains("mc:AlternateContent",StringComparison.Ordinal),"unknown_mc"=>d.Contains("ux:opaque",StringComparison.Ordinal)&&d.Contains("mc:Ignorable",StringComparison.Ordinal),"opaque_custom_part"=>e.ContainsKey("word/custom/opaque.xml")&&rels.Contains("urn:stealtheye:relationships:opaque",StringComparison.Ordinal),"inert_opaque_binary"=>e.ContainsKey("word/embeddings/opaque.bin")&&rels.Contains("urn:stealtheye:relationships:opaque-binary",StringComparison.Ordinal),_=>false
    };
    private static string FeatureEntry(string feature)=>feature switch{"headings_styles"=>"word/styles.xml","nested_restarted_numbering"=>"word/numbering.xml","comments_replies"=>"word/commentsExtended.xml","section_header_footer"=>"word/header1.xml","footnote"=>"word/footnotes.xml","endnote"=>"word/endnotes.xml","figure_media"=>"word/media/image1.png","custom_xml"=>"customXml/item1.xml","opaque_custom_part"=>"word/custom/opaque.xml","inert_opaque_binary"=>"word/embeddings/opaque.bin",_=>"word/document.xml"};
    private static string ExtractSupportedTarget(string document)=>document.Contains("F001_SUPPORTED_EDIT_TARGET",StringComparison.Ordinal)?"F001_SUPPORTED_EDIT_TARGET":throw new InvalidDataException("supported edit marker missing");
    private static string ExtractUnknownChoice(string document){int a=document.IndexOf("<mc:AlternateContent",StringComparison.Ordinal),b=document.IndexOf("</mc:AlternateContent>",StringComparison.Ordinal);if(a<0||b<a)throw new InvalidDataException("alternate content missing");return document[a..(b+"</mc:AlternateContent>".Length)];}
    private static string Utf8(IReadOnlyDictionary<string,byte[]> entries,string name)=>entries.TryGetValue(name,out var bytes)?Encoding.UTF8.GetString(bytes):throw new InvalidDataException("missing entry "+name);
    private static SortedDictionary<string,byte[]> ReadEntries(byte[] source){var result=new SortedDictionary<string,byte[]>(StringComparer.Ordinal);using var ms=new MemoryStream(source,false);using var zip=new ZipArchive(ms,ZipArchiveMode.Read,false,Encoding.UTF8);if(zip.Entries.Count>4096)throw new InvalidDataException("too_many_zip_entries");long total=0;foreach(var entry in zip.Entries){string name=entry.FullName.Replace('\\','/');if(name.Length==0||name.StartsWith("/",StringComparison.Ordinal)||name.Contains("../",StringComparison.Ordinal)||name.Contains("/..",StringComparison.Ordinal)||!result.TryAdd(name,Read(entry)))throw new InvalidDataException("unsafe_or_duplicate_zip_entry:"+name);total+=entry.Length;if(entry.Length>64L*1024*1024||total>512L*1024*1024)throw new InvalidDataException("zip_size_limit");}return result;static byte[] Read(ZipArchiveEntry e){using var s=e.Open();using var m=new MemoryStream();s.CopyTo(m);return m.ToArray();}}
    private static void WriteEntries(string path,IReadOnlyDictionary<string,byte[]> entries){if(File.Exists(path))File.Delete(path);using var fs=File.Create(path);using var zip=new ZipArchive(fs,ZipArchiveMode.Create,false,Encoding.UTF8);foreach(var pair in entries.OrderBy(x=>x.Key,StringComparer.Ordinal)){var e=zip.CreateEntry(pair.Key,CompressionLevel.NoCompression);e.LastWriteTime=new DateTimeOffset(2020,1,1,0,0,0,TimeSpan.Zero);using var s=e.Open();s.Write(pair.Value);}}
    private static IReadOnlyDictionary<string,string> EntryDigests(IReadOnlyDictionary<string,byte[]> entries)=>entries.ToDictionary(k=>k.Key,v=>Convert.ToHexString(SHA256.HashData(v.Value)).ToLowerInvariant(),StringComparer.Ordinal);
    private static void ValidateRelationships(IReadOnlyDictionary<string,byte[]> entries,List<string> errors){foreach(var pair in entries.Where(x=>x.Key.EndsWith(".rels",StringComparison.Ordinal))){XDocument x=XDocument.Parse(Encoding.UTF8.GetString(pair.Value),LoadOptions.PreserveWhitespace);XNamespace r="http://schemas.openxmlformats.org/package/2006/relationships";foreach(var rel in x.Root?.Elements(r+"Relationship")??[]){string type=(string?)rel.Attribute("Type")??"",target=(string?)rel.Attribute("Target")??"",mode=(string?)rel.Attribute("TargetMode")??"Internal";if(mode=="External")continue;if(type.Contains("vbaProject",StringComparison.OrdinalIgnoreCase)||type.Contains("oleObject",StringComparison.OrdinalIgnoreCase)||type.Contains("activeX",StringComparison.OrdinalIgnoreCase))errors.Add("dangerous_relationship:"+type);string resolved=ResolveTarget(pair.Key,target);if(!entries.ContainsKey(resolved))errors.Add("missing_relationship_target:"+resolved);}}}
    private static string ResolveTarget(string relsEntry,string target){string sourcePart=relsEntry=="_rels/.rels"?"":relsEntry.Replace("/_rels/","/",StringComparison.Ordinal).Replace(".rels","",StringComparison.Ordinal);string baseDir=sourcePart.Length==0?"":Path.GetDirectoryName(sourcePart)!.Replace('\\','/');var stack=new List<string>();foreach(string p in (baseDir.Length==0?target:baseDir+"/"+target).Split('/',StringSplitOptions.RemoveEmptyEntries)){if(p==".")continue;if(p==".."){if(stack.Count==0)throw new InvalidDataException("relationship_path_escape");stack.RemoveAt(stack.Count-1);}else stack.Add(p);}return string.Join('/',stack);}
    private static string XmlEscape(string text)=>text.Replace("&","&amp;",StringComparison.Ordinal).Replace("<","&lt;",StringComparison.Ordinal).Replace(">","&gt;",StringComparison.Ordinal).Replace("\"","&quot;",StringComparison.Ordinal).Replace("'","&apos;",StringComparison.Ordinal);
    private static string HashFile(string path){using var fs=File.OpenRead(path);return Convert.ToHexString(SHA256.HashData(fs)).ToLowerInvariant();}
    private static (int exitCode,string stdout,string stderr) Run(string file,IReadOnlyList<string> args,int timeoutMs){var psi=new ProcessStartInfo(file){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true};foreach(string a in args)psi.ArgumentList.Add(a);using var p=Process.Start(psi)??throw new InvalidOperationException("provider_start_failed");Task<string> o=p.StandardOutput.ReadToEndAsync(),e=p.StandardError.ReadToEndAsync();if(!p.WaitForExit(timeoutMs)){try{p.Kill(true);}catch{}throw new TimeoutException("provider_timeout:"+Path.GetFileName(file));}Task.WaitAll(o,e);return(p.ExitCode,o.Result,e.Result);}
}